const VERSION='0.2.0',DB_NAME='little-days-cards-db',STORE='contacts';
let db,contacts=[],activeFilter='all',currentDetailId=null;
const $=id=>document.getElementById(id),nowIso=()=>new Date().toISOString(),uid=()=>crypto.randomUUID?.()||`c_${Date.now()}_${Math.random().toString(36).slice(2)}`;
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=(s='')=>String(s).toLowerCase().normalize('NFKC').trim(),today=()=>new Date().toLocaleDateString('sv-SE');
const tags=v=>Array.isArray(v)?v:String(v||'').split(/[,，、]/).map(x=>x.trim()).filter(Boolean);
const due=c=>!!c.followUpDate&&c.followUpDate<=today(),recent=c=>Date.now()-new Date(c.createdAt||0).getTime()<30*864e5;
const phone=v=>`tel:${String(v||'').replace(/[^\d+]/g,'')}`,safeUrl=v=>/^https?:\/\//i.test(v||'')?v:`https://${v||''}`;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const store=(mode='readonly')=>db.transaction(STORE,mode).objectStore(STORE);
const dbAll=()=>new Promise((res,rej)=>{const r=store().getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});
const dbPut=x=>new Promise((res,rej)=>{const r=store('readwrite').put(x);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const dbDelete=id=>new Promise((res,rej)=>{const r=store('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
function initials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);return !p.length?'名':p.length>1?(p[0][0]+p.at(-1)[0]).toUpperCase():p[0].slice(0,2).toUpperCase()}
function fmtDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v+'T12:00:00'))}catch{return v}}
async function reload(){contacts=await dbAll();render()}
function filtered(){const q=norm($('searchInput').value);let a=contacts.filter(c=>{if(activeFilter==='favorite'&&!c.favorite)return false;if(activeFilter==='followup'&&!due(c))return false;if(activeFilter==='recent'&&!recent(c))return false;if(!q)return true;return norm([c.name,c.company,c.title,c.department,c.mobile,c.phone,c.email,c.messenger,c.website,c.address,c.context,c.project,c.notes,...tags(c.tags)].join(' ')).includes(q)});const s=$('sortSelect').value,txt=(a,b,k)=>String(a[k]||'').localeCompare(String(b[k]||''),'zh-Hant');if(s==='created-desc')a.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));else if(s==='name-asc')a.sort((x,y)=>txt(x,y,'name'));else if(s==='company-asc')a.sort((x,y)=>txt(x,y,'company'));else a.sort((x,y)=>new Date(y.updatedAt)-new Date(x.updatedAt));return a}
function card(c){const ts=tags(c.tags).slice(0,3),img=c.photoData?`<img src="${c.photoData}" alt="${esc(c.name)}名片照片">`:esc(initials(c.name)),meta=[c.company,c.title].filter(Boolean).join(' · ')||c.email||c.mobile||'尚未補充公司資訊';return `<button class="contact-card" data-id="${esc(c.id)}"><span class="avatar">${img}</span><span class="contact-main"><strong>${esc(c.name)}</strong><span class="meta">${esc(meta)}</span>${ts.length?`<span class="tagline">${ts.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</span>`:''}</span><span class="card-side">${c.favorite?'<span class="star">★</span>':''}${due(c)?'<span class="followup-pill">待追蹤</span>':''}<span>›</span></span></button>`}
function render(){$('totalCount').textContent=contacts.length;$('favoriteCount').textContent=contacts.filter(x=>x.favorite).length;$('followupCount').textContent=contacts.filter(due).length;$('listTitle').textContent={all:'所有名片',favorite:'最愛名片',followup:'待追蹤',recent:'最近新增'}[activeFilter];const a=filtered();$('contactsList').innerHTML=a.map(card).join('');$('emptyState').classList.toggle('hidden',contacts.length!==0||$('searchInput').value||activeFilter!=='all');if(contacts.length&&!a.length)$('contactsList').innerHTML='<div class="empty-state"><div class="empty-icon">⌕</div><h3>找不到符合的名片</h3><p>換個關鍵字或篩選條件試試看。</p></div>'}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function openDlg(id){const d=$(id);if(!d.open)d.showModal()}function closeDlg(id){const d=$(id);if(d.open)d.close()}
function resetForm(){$('contactForm').reset();$('contactId').value='';$('photoData').value='';$('photoPreview').innerHTML='<span>名片照片</span>';$('removePhotoBtn').classList.add('hidden');$('deleteBtn').classList.add('hidden');$('editTitle').textContent='新增名片'}
function openNew(){resetForm();openDlg('editDialog')}
function fillForm(c){resetForm();$('editTitle').textContent='編輯名片';$('contactId').value=c.id;$('deleteBtn').classList.remove('hidden');['name','company','title','department','mobile','phone','email','messenger','website','address','context','project','followUpDate','notes'].forEach(k=>$(k).value=c[k]||'');$('tags').value=tags(c.tags).join(', ');$('favorite').checked=!!c.favorite;$('photoData').value=c.photoData||'';if(c.photoData){$('photoPreview').innerHTML=`<img src="${c.photoData}" alt="名片照片">`;$('removePhotoBtn').classList.remove('hidden')}}
function formData(){const id=$('contactId').value||uid(),old=contacts.find(x=>x.id===id),get=k=>$(k).value.trim();return{id,name:get('name'),company:get('company'),title:get('title'),department:get('department'),mobile:get('mobile'),phone:get('phone'),email:get('email'),messenger:get('messenger'),website:get('website'),address:get('address'),context:get('context'),project:get('project'),tags:tags(get('tags')),followUpDate:get('followUpDate'),notes:get('notes'),favorite:$('favorite').checked,photoData:$('photoData').value,createdAt:old?.createdAt||nowIso(),updatedAt:nowIso()}}
async function saveForm(e){e.preventDefault();const x=formData();if(!x.name)return;await dbPut(x);closeDlg('editDialog');await reload();toast('名片已儲存')}
async function delCurrent(){const id=$('contactId').value;if(!id||!confirm('確定要刪除這張名片嗎？'))return;await dbDelete(id);closeDlg('editDialog');closeDlg('detailDialog');await reload();toast('名片已刪除')}
function compress(file,max=1400,q=.78){return new Promise((res,rej)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight,s=Math.min(1,max/Math.max(w,h));w=Math.round(w*s);h=Math.round(h*s);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',q))};img.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('decode'))};img.src=u})}
async function readPhoto(file){if(!file)return;if(file.size>15*1024*1024)return toast('圖片太大，請選較小的照片');try{const d=await compress(file);$('photoData').value=d;$('photoPreview').innerHTML=`<img src="${d}" alt="名片照片預覽">`;$('removePhotoBtn').classList.remove('hidden')}catch{toast('照片讀取失敗')}}
function showDetail(id){const c=contacts.find(x=>x.id===id);if(!c)return;currentDetailId=id;$('detailName').textContent=c.name;const photo=c.photoData?`<img class="detail-photo" src="${c.photoData}" alt="${esc(c.name)}名片照片">`:'',ts=tags(c.tags),acts=[];if(c.mobile||c.phone)acts.push(`<a class="action-button" href="${phone(c.mobile||c.phone)}">撥電話</a>`);if(c.email)acts.push(`<a class="action-button" href="mailto:${encodeURIComponent(c.email)}">寄 Email</a>`);if(c.address)acts.push(`<a class="action-button" target="_blank" rel="noopener" href="https://maps.apple.com/?q=${encodeURIComponent(c.address)}">開地圖</a>`);const rows=[],add=(l,v,h='')=>{if(v)rows.push(`<div class="info-row"><span>${l}</span><span>${h||esc(v)}</span></div>`)};add('公司',c.company);add('職稱',[c.department,c.title].filter(Boolean).join(' / '));add('手機',c.mobile,c.mobile?`<a href="${phone(c.mobile)}">${esc(c.mobile)}</a>`:'');add('電話',c.phone,c.phone?`<a href="${phone(c.phone)}">${esc(c.phone)}</a>`:'');add('Email',c.email,c.email?`<a href="mailto:${encodeURIComponent(c.email)}">${esc(c.email)}</a>`:'');add('通訊',c.messenger);add('網站',c.website,c.website?`<a target="_blank" rel="noopener" href="${esc(safeUrl(c.website))}">${esc(c.website)}</a>`:'');add('地址',c.address);add('場合',c.context);add('專案',c.project);add('追蹤',c.followUpDate,fmtDate(c.followUpDate));$('detailContent').innerHTML=`${photo}<div class="detail-meta"><h3>${esc(c.name)}</h3><p>${esc([c.company,c.title].filter(Boolean).join(' · '))}</p>${ts.length?`<div class="tagline">${ts.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`:''}</div>${acts.length?`<div class="action-grid">${acts.join('')}</div>`:''}<div class="info-list">${rows.join('')}</div>${c.notes?`<div class="notes-card">${esc(c.notes)}</div>`:''}`;$('detailFavoriteBtn').textContent=c.favorite?'★ 已加入最愛':'☆ 加入最愛';openDlg('detailDialog')}
async function toggleFavorite(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;c.favorite=!c.favorite;c.updatedAt=nowIso();await dbPut(c);await reload();$('detailFavoriteBtn').textContent=c.favorite?'★ 已加入最愛':'☆ 加入最愛';toast(c.favorite?'已加入最愛':'已移除最愛')}
function editDetail(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;closeDlg('detailDialog');fillForm(c);openDlg('editDialog')}
function vcard(c){return ['BEGIN:VCARD','VERSION:3.0',`FN:${c.name||''}`,c.company?`ORG:${c.company}`:'',c.title?`TITLE:${c.title}`:'',c.mobile?`TEL;TYPE=CELL:${c.mobile}`:'',c.phone?`TEL;TYPE=WORK:${c.phone}`:'',c.email?`EMAIL:${c.email}`:'',c.website?`URL:${safeUrl(c.website)}`:'',c.address?`ADR;TYPE=WORK:;;${c.address};;;;`:'',c.notes?`NOTE:${c.notes.replace(/\n/g,'\\n')}`:'','END:VCARD'].filter(Boolean).join('\r\n')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
async function shareCurrent(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;const blob=new Blob([vcard(c)],{type:'text/vcard'}),file=new File([blob],`${c.name||'contact'}.vcf`,{type:'text/vcard'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({title:c.name,text:[c.company,c.title].filter(Boolean).join(' · '),files:[file]});else{download(blob,file.name);toast('已匯出 vCard')}}catch(e){if(e.name!=='AbortError')toast('分享失敗')}}
function backup(){const x={app:'little-days-cards',version:VERSION,exportedAt:nowIso(),contacts};download(new Blob([JSON.stringify(x,null,2)],{type:'application/json'}),`人脈名片備份_${today()}.json`);toast('備份已匯出')}
async function restoreFile(file){if(!file)return;try{const x=JSON.parse(await file.text());if(!Array.isArray(x.contacts))throw 0;if(!confirm(`找到 ${x.contacts.length} 筆名片。\n\n按「確定」：加入／更新現有資料\n按「取消」：不匯入`))return;for(const c of x.contacts)await dbPut({...c,id:c.id||uid(),createdAt:c.createdAt||nowIso(),updatedAt:c.updatedAt||nowIso()});await reload();closeDlg('toolsDialog');toast(`已匯入 ${x.contacts.length} 筆`)}catch{alert('這不是有效的人脈名片備份檔。')}}
const csvCell=v=>`"${(Array.isArray(v)?v.join('|'):String(v??'')).replace(/"/g,'""')}"`;
function exportCsv(){const h=['姓名','公司','職稱','部門','手機','電話','Email','通訊','網站','地址','場合','專案','標籤','下次追蹤','最愛','備註','建立時間','更新時間'],r=contacts.map(c=>[c.name,c.company,c.title,c.department,c.mobile,c.phone,c.email,c.messenger,c.website,c.address,c.context,c.project,tags(c.tags),c.followUpDate,c.favorite?'是':'否',c.notes,c.createdAt,c.updatedAt]),csv='\ufeff'+[h,...r].map(x=>x.map(csvCell).join(',')).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),`人脈名片_${today()}.csv`);toast('CSV 已匯出')}
async function seedDemo(){const a=[{name:'陳怡君',company:'新北市政府',title:'科長',department:'交通規劃科',mobile:'0912-345-678',email:'yijun@example.gov.tw',context:'專案會議',project:'自行車路網',tags:['公部門','新北','自行車'],followUpDate:today(),favorite:true,notes:'關心轉乘節點與斷鏈改善。'},{name:'林志宏',company:'遠見工程顧問',title:'協理',mobile:'0933-222-111',email:'jhlin@example.com',context:'研討會',project:'交流道改善',tags:['顧問','道路'],favorite:false,notes:'後續可討論綜規合作。'},{name:'Amy Wang',company:'Urban Mobility Lab',title:'Project Manager',email:'amy@example.com',context:'論壇',tags:['國際','Mobility'],favorite:false,notes:'英文聯繫。'}];for(const d of a)await dbPut({...d,id:uid(),photoData:'',phone:'',messenger:'',website:'',address:'',department:d.department||'',createdAt:nowIso(),updatedAt:nowIso()});await reload();toast('已載入示範資料')}
function setFilter(f){activeFilter=f;document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));document.querySelectorAll('.nav-item[data-nav]').forEach(b=>b.classList.remove('active'));if(f==='all')document.querySelector('[data-nav="contacts"]')?.classList.add('active');if(f==='favorite')document.querySelector('[data-nav="favorites"]')?.classList.add('active');if(f==='followup')document.querySelector('[data-nav="followup"]')?.classList.add('active');render();window.scrollTo({top:0,behavior:'smooth'})}
function bind(){['scanBtn','emptyAddBtn','fabAdd'].forEach(id=>$(id).addEventListener('click',openNew));$('contactForm').addEventListener('submit',saveForm);$('deleteBtn').addEventListener('click',delCurrent);$('takePhotoBtn').onclick=()=>$('cameraInput').click();$('choosePhotoBtn').onclick=()=>$('photoInput').click();['cameraInput','photoInput'].forEach(id=>$(id).addEventListener('change',async e=>{await readPhoto(e.target.files[0]);e.target.value=''}));$('removePhotoBtn').onclick=()=>{$('photoData').value='';$('photoPreview').innerHTML='<span>名片照片</span>';$('removePhotoBtn').classList.add('hidden')};document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>closeDlg(b.dataset.closeDialog));$('contactsList').onclick=e=>{const c=e.target.closest('.contact-card');if(c)showDetail(c.dataset.id)};$('searchInput').oninput=()=>{$('searchInput').parentElement.classList.toggle('has-text',!!$('searchInput').value);render()};$('clearSearch').onclick=()=>{$('searchInput').value='';$('searchInput').parentElement.classList.remove('has-text');render();$('searchInput').focus()};$('sortSelect').onchange=render;document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));document.querySelectorAll('.nav-item[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='contacts')setFilter('all');else if(n==='followup')setFilter('followup');else if(n==='favorites')setFilter('favorite');else if(n==='tools')openDlg('toolsDialog')});$('settingsBtn').onclick=()=>openDlg('toolsDialog');$('backupBtn').onclick=backup;$('restoreBtn').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=async e=>{await restoreFile(e.target.files[0]);e.target.value=''};$('csvBtn').onclick=exportCsv;$('seedDemoBtn').onclick=seedDemo;$('detailFavoriteBtn').onclick=toggleFavorite;$('detailEditBtn').onclick=editDetail;$('detailShareBtn').onclick=shareCurrent;document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}))}
async function init(){try{db=await openDB();bind();await reload();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){console.error(e);alert('無法啟動本機資料庫，請確認瀏覽器允許網站儲存資料。')}}
init();
