const VERSION='0.3.0',DB_NAME='little-days-cards-db',STORE='contacts',MY_CARD_KEY='little-days-cards-my-card';
let db,contacts=[],activeFilter='all',currentDetailId=null,currentMode='quick',ocrBusy=false;
const $=id=>document.getElementById(id);
const nowIso=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID?crypto.randomUUID():'c_'+Date.now()+'_'+Math.random().toString(36).slice(2);
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=(s='')=>String(s).toLowerCase().normalize('NFKC').trim();
const today=()=>new Date().toLocaleDateString('sv-SE');
const tags=v=>Array.isArray(v)?v:String(v||'').split(/[,，、|]/).map(x=>x.trim()).filter(Boolean);
const due=c=>!!c.followUpDate&&c.followUpDate<=today();
const recent=c=>Date.now()-new Date(c.createdAt||0).getTime()<30*864e5;
const phone=v=>'tel:'+String(v||'').replace(/[^\d+]/g,'');
const safeUrl=v=>/^https?:\/\//i.test(v||'')?v:'https://'+(v||'');
const interactions=c=>Array.isArray(c.interactions)?c.interactions:[];
const lastInteraction=c=>interactions(c).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0];

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const store=(m='readonly')=>db.transaction(STORE,m).objectStore(STORE);
const dbAll=()=>new Promise((res,rej)=>{const r=store().getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});
const dbPut=x=>new Promise((res,rej)=>{const r=store('readwrite').put(x);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const dbDelete=id=>new Promise((res,rej)=>{const r=store('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});

function initials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);return !p.length?'名':p.length>1?(p[0][0]+p[p.length-1][0]).toUpperCase():p[0].slice(0,2).toUpperCase()}
function fmtDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v+'T12:00:00'))}catch(e){return v}}
function daysUntil(v){if(!v)return null;return Math.round((new Date(v+'T00:00:00')-new Date(today()+'T00:00:00'))/864e5)}
function touchLabel(c){const i=lastInteraction(c);if(!i)return'';const d=daysUntil(i.date);if(d===0)return'今天互動';if(d===-1)return'昨天互動';if(d<0&&d>=-7)return Math.abs(d)+' 天前互動';return fmtDate(i.date)}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
function openDlg(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDlg(id){const d=$(id);if(d&&d.open)d.close()}

async function reload(){contacts=(await dbAll()).map(c=>Object.assign({},c,{interactions:interactions(c)}));render()}
function filtered(){const q=norm($('searchInput').value);let a=contacts.filter(c=>{if(activeFilter==='favorite'&&!c.favorite)return false;if(activeFilter==='followup'&&!due(c))return false;if(activeFilter==='recent'&&!recent(c))return false;if(!q)return true;return norm([c.name,c.company,c.title,c.department,c.mobile,c.phone,c.email,c.messenger,c.website,c.address,c.context,c.project,c.notes].concat(tags(c.tags),interactions(c).flatMap(i=>[i.type,i.note,i.date])).join(' ')).includes(q)});const s=$('sortSelect').value;if(s==='created-desc')a.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));else if(s==='interaction-desc')a.sort((x,y)=>String((lastInteraction(y)||{}).date||'').localeCompare(String((lastInteraction(x)||{}).date||'')));else if(s==='name-asc')a.sort((x,y)=>String(x.name||'').localeCompare(String(y.name||''),'zh-Hant'));else if(s==='company-asc')a.sort((x,y)=>String(x.company||'').localeCompare(String(y.company||''),'zh-Hant'));else a.sort((x,y)=>new Date(y.updatedAt)-new Date(x.updatedAt));return a}
function card(c){const ts=tags(c.tags).slice(0,2),img=c.photoData?'<img src="'+c.photoData+'" alt="'+esc(c.name)+'名片照片">':esc(initials(c.name)),meta=[c.company,c.title].filter(Boolean).join(' · ')||c.email||c.mobile||'尚未補充公司資訊',touch=touchLabel(c);return '<button class="contact-card" data-id="'+esc(c.id)+'"><span class="avatar">'+img+'</span><span class="contact-main"><strong>'+esc(c.name)+'</strong><span class="meta">'+esc(meta)+'</span>'+(ts.length?'<span class="tagline">'+ts.map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</span>':'')+'</span><span class="card-side">'+(c.favorite?'<span class="star">★</span>':'')+(due(c)?'<span class="followup-pill">待追蹤</span>':'')+(touch?'<span class="last-touch">'+esc(touch)+'</span>':'')+'<span>›</span></span></button>'}
function render(){const fav=contacts.filter(x=>x.favorite).length,dues=contacts.filter(due).length,intCount=contacts.reduce((n,c)=>n+interactions(c).length,0);$('totalCount').textContent=contacts.length;$('favoriteCount').textContent=fav;$('followupCount').textContent=dues;$('interactionCount').textContent=intCount;$('listTitle').textContent={all:'所有人脈',favorite:'最愛人脈',followup:'待追蹤',recent:'最近新增'}[activeFilter];const a=filtered();$('contactsList').innerHTML=a.map(card).join('');$('emptyState').classList.toggle('hidden',contacts.length!==0||$('searchInput').value||activeFilter!=='all');if(contacts.length&&!a.length)$('contactsList').innerHTML='<div class="empty-state"><div class="empty-icon">⌕</div><h3>找不到符合的人</h3><p>換個名字、公司、專案、場合或標籤試試看。</p></div>';$('dueSpotlight').classList.toggle('hidden',!dues);if(dues)$('dueSpotlightText').textContent='有 '+dues+' 位人脈需要追蹤，別讓關係斷掉。'}

function setMode(mode){currentMode=mode;const scan=mode==='scan'||mode==='edit-scan';$('scanPanel').classList.toggle('hidden',!scan);$('editEyebrow').textContent=scan?'SMART SCAN':'QUICK ADD';$('editTitle').textContent=mode.indexOf('edit')===0?'編輯名片':scan?'掃描名片':'快速新增';$('formIntro').querySelector('strong').textContent=scan?'辨識後只要確認幾個重點。':'只要確認幾個重點就能存。'}
function resetForm(){$('contactForm').reset();$('contactId').value='';$('photoData').value='';$('ocrRawText').value='';$('photoPreview').innerHTML='<span class="photo-placeholder-icon">▣</span><span>拍一張名片，讓我幫你讀</span>';$('removePhotoBtn').classList.add('hidden');$('ocrBtn').classList.add('hidden');$('ocrProgress').classList.add('hidden');$('rawOcrDetails').classList.add('hidden');$('deleteBtn').classList.add('hidden');$('advancedDetails').open=false}
function openQuick(){closeDlg('captureChoiceDialog');resetForm();setMode('quick');openDlg('editDialog')}
function openScan(){closeDlg('captureChoiceDialog');resetForm();setMode('scan');openDlg('editDialog')}
function fillForm(c){resetForm();setMode(c.photoData?'edit-scan':'edit');$('contactId').value=c.id;$('deleteBtn').classList.remove('hidden');['name','company','title','department','mobile','phone','email','messenger','website','address','context','project','followUpDate','notes'].forEach(k=>$(k).value=c[k]||'');$('tags').value=tags(c.tags).join(', ');$('favorite').checked=!!c.favorite;$('photoData').value=c.photoData||'';$('ocrRawText').value=c.ocrRawText||'';if(c.photoData){$('photoPreview').innerHTML='<img src="'+c.photoData+'" alt="名片照片">';$('removePhotoBtn').classList.remove('hidden');$('ocrBtn').classList.remove('hidden')}if(c.ocrRawText){$('rawOcrText').textContent=c.ocrRawText;$('rawOcrDetails').classList.remove('hidden')}}
function formData(){const id=$('contactId').value||uid(),old=contacts.find(x=>x.id===id),get=k=>$(k).value.trim();return{id,name:get('name'),company:get('company'),title:get('title'),department:get('department'),mobile:get('mobile'),phone:get('phone'),email:get('email'),messenger:get('messenger'),website:get('website'),address:get('address'),context:get('context'),project:get('project'),tags:tags(get('tags')),followUpDate:get('followUpDate'),notes:get('notes'),favorite:$('favorite').checked,photoData:$('photoData').value,ocrRawText:$('ocrRawText').value,interactions:old?interactions(old):[],createdAt:old?old.createdAt:nowIso(),updatedAt:nowIso()}}
function findDuplicate(x){return contacts.find(c=>c.id!==x.id&&((x.email&&c.email&&norm(x.email)===norm(c.email))||(x.mobile&&c.mobile&&x.mobile.replace(/\D/g,'')===c.mobile.replace(/\D/g,''))||(x.name&&x.company&&norm(x.name)===norm(c.name)&&norm(x.company)===norm(c.company))))}
function mergeContact(a,b){const p=(x,y)=>x||y;return Object.assign({},a,{name:p(b.name,a.name),company:p(b.company,a.company),title:p(b.title,a.title),department:p(b.department,a.department),mobile:p(b.mobile,a.mobile),phone:p(b.phone,a.phone),email:p(b.email,a.email),messenger:p(b.messenger,a.messenger),website:p(b.website,a.website),address:p(b.address,a.address),context:p(b.context,a.context),project:p(b.project,a.project),tags:[...new Set(tags(a.tags).concat(tags(b.tags)))],followUpDate:p(b.followUpDate,a.followUpDate),notes:[a.notes,b.notes].filter(Boolean).filter((v,i,z)=>z.indexOf(v)===i).join('\n'),favorite:!!(a.favorite||b.favorite),photoData:p(b.photoData,a.photoData),ocrRawText:p(b.ocrRawText,a.ocrRawText),interactions:interactions(a).concat(interactions(b)).sort((x,y)=>String(y.date).localeCompare(String(x.date))),updatedAt:nowIso()})}
async function saveForm(e){e.preventDefault();let x=formData();if(!x.name)return toast('至少要有姓名');const originalId=x.id,dup=findDuplicate(x);let merged=false;if(dup&&confirm('看起來「'+dup.name+'」已經存在。\n\n要把這次資料合併到既有人脈嗎？')){x=mergeContact(dup,x);merged=true}await dbPut(x);if(merged&&originalId!==x.id)await dbDelete(originalId);closeDlg('editDialog');await reload();toast(merged?'已合併並儲存':'已快速儲存')}
async function delCurrent(){const id=$('contactId').value;if(!id||!confirm('確定要刪除這張名片嗎？'))return;await dbDelete(id);closeDlg('editDialog');closeDlg('detailDialog');await reload();toast('名片已刪除')}

function compress(file,max=1600,q=.82){return new Promise((res,rej)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight,s=Math.min(1,max/Math.max(w,h));w=Math.round(w*s);h=Math.round(h*s);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',q))};img.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('decode'))};img.src=u})}
async function readPhoto(file){if(!file)return;if(file.size>20*1024*1024)return toast('圖片太大，請選較小的照片');try{const d=await compress(file);$('photoData').value=d;$('photoPreview').innerHTML='<img src="'+d+'" alt="名片照片預覽">';$('removePhotoBtn').classList.remove('hidden');$('ocrBtn').classList.remove('hidden');if(currentMode==='scan')setTimeout(runOCR,180)}catch(e){toast('照片讀取失敗')}}
function loadScript(src,test){return new Promise((res,rej)=>{if(test())return res();const s=document.createElement('script');s.src=src;s.onload=()=>test()?res():rej(new Error('load'));s.onerror=rej;document.head.appendChild(s)})}
function setOcrProgress(p,text){$('ocrProgress').classList.remove('hidden');$('ocrProgressBar').style.width=Math.max(3,Math.round(p*100))+'%';$('ocrProgressText').textContent=text||'辨識中…'}
function parseBusinessCard(raw){const lines=raw.split(/\r?\n/).map(x=>x.replace(/[|｜]/g,' ').replace(/\s+/g,' ').trim()).filter(x=>x.length>1),joined=lines.join(' '),email=(joined.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'',urls=joined.match(/(?:https?:\/\/|www\.)[^\s]+/ig)||[],website=urls.find(x=>!x.includes('@'))||'',pm=joined.match(/(?:\+?\d[\d\s().-]{7,}\d)/g)||[],phones=[...new Set(pm.map(x=>x.trim()).filter(x=>x.replace(/\D/g,'').length>=8))],mobile=phones.find(x=>/09\d{8}|9\d{8}/.test(x.replace(/\D/g,'')))||phones[0]||'',phone2=phones.find(x=>x!==mobile)||'',companyRx=/(股份有限公司|有限公司|公司|集團|基金會|協會|公會|局|處|部|中心|研究院|工程顧問|科技|建設|銀行|醫院|大學|Inc\.?|Ltd\.?|Corp\.?|Company|Group|Consult)/i,titleRx=/(董事長|總經理|副總|協理|經理|副理|處長|科長|組長|主任|工程師|顧問|專員|教授|Project Manager|Product Manager|Manager|Director|Engineer|Consultant|President|CEO|CTO|CFO|VP)/i,addressRx=/(台灣|臺灣|台北|臺北|新北|桃園|新竹|台中|臺中|彰化|嘉義|台南|臺南|高雄|宜蘭|花蓮|市|縣|區|鄉|鎮|路|街|巷|號|Taiwan|Taipei|Taoyuan|Hsinchu|Taichung|Kaohsiung)/i,company=lines.find(x=>companyRx.test(x))||'',title=lines.find(x=>titleRx.test(x)&&x!==company)||'',address=lines.find(x=>addressRx.test(x)&&/\d/.test(x)&&x!==mobile&&x!==phone2)||'';let name=lines.find(x=>/^[\u3400-\u9fff·]{2,5}$/.test(x)&&!companyRx.test(x)&&!titleRx.test(x));if(!name)name=lines.find(x=>/^[A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,2}$/.test(x));if(!name)name=lines.find(x=>x.length>=2&&x.length<=18&&!/[\d@]/.test(x)&&!companyRx.test(x)&&!titleRx.test(x)&&!addressRx.test(x))||'';return{name,company,title,mobile,phone:phone2,email,website:website.replace(/[),.;]+$/,''),address}}
function applyOcrFields(x){Object.entries(x).forEach(([k,v])=>{if(v&&$(k)&&!$(k).value.trim())$(k).value=v});if(x.title||x.website||x.address)$('advancedDetails').open=true}
async function runOCR(){if(ocrBusy||!$('photoData').value)return;ocrBusy=true;$('ocrBtn').disabled=true;setOcrProgress(.03,'載入辨識元件…');try{await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',()=>!!window.Tesseract);setOcrProgress(.08,'準備中文／英文辨識…');const r=await Tesseract.recognize($('photoData').value,'chi_tra+eng',{logger:m=>{if(m.status==='recognizing text')setOcrProgress(.12+(m.progress||0)*.84,'辨識中 '+Math.round((m.progress||0)*100)+'%')}}),raw=(r.data&&r.data.text?r.data.text:'').trim();$('ocrRawText').value=raw;$('rawOcrText').textContent=raw;$('rawOcrDetails').classList.toggle('hidden',!raw);applyOcrFields(parseBusinessCard(raw));setOcrProgress(1,'完成，請快速確認姓名與聯絡方式');toast('名片辨識完成')}catch(e){console.error(e);setOcrProgress(.01,'辨識失敗，可先手動補幾個欄位');toast('OCR 暫時失敗，照片仍已保留')}finally{ocrBusy=false;$('ocrBtn').disabled=false;setTimeout(()=>$('ocrProgress').classList.add('hidden'),3200)}}

function showDetail(id){const c=contacts.find(x=>x.id===id);if(!c)return;currentDetailId=id;$('detailName').textContent=c.name;const photo=c.photoData?'<img class="detail-photo" src="'+c.photoData+'" alt="'+esc(c.name)+'名片照片">':'',ts=tags(c.tags),acts=[];if(c.mobile||c.phone)acts.push('<a class="action-button" href="'+phone(c.mobile||c.phone)+'">撥電話</a>');if(c.email)acts.push('<a class="action-button" href="mailto:'+encodeURIComponent(c.email)+'">寄 Email</a>');if(c.address)acts.push('<a class="action-button" target="_blank" rel="noopener" href="https://maps.apple.com/?q='+encodeURIComponent(c.address)+'">開地圖</a>');const rows=[],add=(l,v,h)=>{if(v)rows.push('<div class="info-row"><span>'+l+'</span><span>'+(h||esc(v))+'</span></div>')};add('公司',c.company);add('職稱',[c.department,c.title].filter(Boolean).join(' / '));add('手機',c.mobile,c.mobile?'<a href="'+phone(c.mobile)+'">'+esc(c.mobile)+'</a>':'');add('電話',c.phone,c.phone?'<a href="'+phone(c.phone)+'">'+esc(c.phone)+'</a>':'');add('Email',c.email,c.email?'<a href="mailto:'+encodeURIComponent(c.email)+'">'+esc(c.email)+'</a>':'');add('通訊',c.messenger);add('網站',c.website,c.website?'<a target="_blank" rel="noopener" href="'+esc(safeUrl(c.website))+'">'+esc(c.website)+'</a>':'');add('地址',c.address);add('場合',c.context);add('專案',c.project);add('追蹤',c.followUpDate,fmtDate(c.followUpDate));$('detailContent').innerHTML=photo+'<div class="detail-meta"><h3>'+esc(c.name)+'</h3><p>'+esc([c.company,c.title].filter(Boolean).join(' · '))+'</p>'+(ts.length?'<div class="tagline">'+ts.map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</div>':'')+'</div>'+(acts.length?'<div class="action-grid">'+acts.join('')+'</div>':'')+'<div class="info-list">'+rows.join('')+'</div>'+(c.notes?'<div class="notes-card">'+esc(c.notes)+'</div>':'');$('detailFavoriteBtn').textContent=c.favorite?'★ 已加入最愛':'☆ 加入最愛';$('interactionComposer').classList.add('hidden');renderTimeline(c);openDlg('detailDialog')}
function renderTimeline(c){const a=interactions(c).slice().sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));$('timelineList').innerHTML=a.length?a.map(i=>'<article class="timeline-item"><strong>'+esc(i.type||'互動')+'</strong><span>'+esc(fmtDate(i.date))+'</span><p>'+esc(i.note||'')+'</p></article>').join(''):'<div class="timeline-empty">還沒有互動紀錄。下一次聯絡後記一句，就不會忘記談過什麼。</div>'}
async function toggleFavorite(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;c.favorite=!c.favorite;c.updatedAt=nowIso();await dbPut(c);await reload();$('detailFavoriteBtn').textContent=c.favorite?'★ 已加入最愛':'☆ 加入最愛';toast(c.favorite?'已加入最愛':'已移除最愛')}
function editDetail(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;closeDlg('detailDialog');fillForm(c);openDlg('editDialog')}
async function saveInteraction(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;const note=$('interactionNote').value.trim();if(!note)return toast('寫一句這次互動的重點');c.interactions=interactions(c).concat([{id:uid(),date:$('interactionDate').value||today(),type:$('interactionType').value,note,createdAt:nowIso()}]);c.updatedAt=nowIso();await dbPut(c);await reload();renderTimeline(c);$('interactionNote').value='';$('interactionComposer').classList.add('hidden');toast('互動已記下')}

function vcard(c){return ['BEGIN:VCARD','VERSION:3.0','FN:'+(c.name||''),c.company?'ORG:'+c.company:'',c.title?'TITLE:'+c.title:'',c.mobile?'TEL;TYPE=CELL:'+c.mobile:'',c.phone?'TEL;TYPE=WORK:'+c.phone:'',c.email?'EMAIL:'+c.email:'',c.website?'URL:'+safeUrl(c.website):'',c.address?'ADR;TYPE=WORK:;;'+c.address+';;;;':'',c.notes?'NOTE:'+c.notes.replace(/\n/g,'\\n'):'','END:VCARD'].filter(Boolean).join('\r\n')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},900)}
async function shareVcard(c){const blob=new Blob([vcard(c)],{type:'text/vcard'}),file=new File([blob],(c.name||'contact')+'.vcf',{type:'text/vcard'});try{if(navigator.canShare&&navigator.canShare({files:[file]}))await navigator.share({title:c.name,text:[c.company,c.title].filter(Boolean).join(' · '),files:[file]});else download(blob,file.name)}catch(e){if(e.name!=='AbortError')toast('分享失敗')}}
async function shareCurrent(){const c=contacts.find(x=>x.id===currentDetailId);if(c)await shareVcard(c)}
function addCalendar(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;if(!c.followUpDate)return toast('先在「編輯」設定下次追蹤日期');const d=c.followUpDate.replace(/-/g,''),next=new Date(c.followUpDate+'T00:00:00');next.setDate(next.getDate()+1);const de=next.toLocaleDateString('sv-SE').replace(/-/g,''),ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Little Days//Cards//ZH-TW','BEGIN:VEVENT','UID:'+uid()+'@little-days','DTSTART;VALUE=DATE:'+d,'DTEND;VALUE=DATE:'+de,'SUMMARY:追蹤 '+c.name,'DESCRIPTION:'+(c.notes||'與 '+c.name+' 聯絡').replace(/\n/g,'\\n'),'END:VEVENT','END:VCALENDAR'].join('\r\n');download(new Blob([ics],{type:'text/calendar'}),'追蹤_'+c.name+'_'+c.followUpDate+'.ics');toast('已建立行事曆事件檔')}

async function backup(){const x={app:'little-days-cards',version:VERSION,exportedAt:nowIso(),myCard:getMyCard(),contacts},blob=new Blob([JSON.stringify(x,null,2)],{type:'application/json'}),file=new File([blob],'人脈名片備份_'+today()+'.json',{type:'application/json'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:'人脈名片備份',files:[file]});toast('可儲存到 iCloud Drive／檔案')}else{download(blob,file.name);toast('備份已匯出')}}catch(e){if(e.name!=='AbortError')download(blob,file.name)}}
async function restoreFile(file){if(!file)return;try{const x=JSON.parse(await file.text());if(!Array.isArray(x.contacts))throw 0;if(!confirm('找到 '+x.contacts.length+' 筆人脈。\n\n按「確定」會加入／更新現有資料。'))return;for(const c of x.contacts)await dbPut(Object.assign({},c,{id:c.id||uid(),interactions:interactions(c),createdAt:c.createdAt||nowIso(),updatedAt:c.updatedAt||nowIso()}));if(x.myCard)localStorage.setItem(MY_CARD_KEY,JSON.stringify(x.myCard));await reload();closeDlg('toolsDialog');toast('已匯入 '+x.contacts.length+' 筆')}catch(e){alert('這不是有效的人脈名片備份檔。')}}
const csvCell=v=>'"'+(Array.isArray(v)?v.join('|'):String(v==null?'':v)).replace(/"/g,'""')+'"';
function exportCsv(){const h=['姓名','公司','職稱','部門','手機','電話','Email','通訊','網站','地址','場合','專案','標籤','下次追蹤','最愛','備註','互動次數','最後互動','建立時間','更新時間'],rows=contacts.map(c=>[c.name,c.company,c.title,c.department,c.mobile,c.phone,c.email,c.messenger,c.website,c.address,c.context,c.project,tags(c.tags),c.followUpDate,c.favorite?'是':'否',c.notes,interactions(c).length,(lastInteraction(c)||{}).date||'',c.createdAt,c.updatedAt]),csv='\ufeff'+[h].concat(rows).map(x=>x.map(csvCell).join(',')).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),'人脈名片_'+today()+'.csv');toast('CSV 已匯出')}

function parseVcards(text){return text.split(/(?=BEGIN:VCARD)/i).filter(x=>/BEGIN:VCARD/i.test(x)).map(block=>{const lines=block.replace(/\r\n[ \t]/g,'').split(/\r?\n/),get=key=>{const l=lines.find(x=>new RegExp('^'+key+'(?:;[^:]*)?:','i').test(x));return l?l.slice(l.indexOf(':')+1).replace(/\\n/g,'\n').trim():''},tels=lines.filter(x=>/^TEL/i.test(x)).map(x=>x.slice(x.indexOf(':')+1).trim());return{id:uid(),name:get('FN')||get('N').split(';').filter(Boolean).reverse().join(' '),company:get('ORG').replace(/;/g,' '),title:get('TITLE'),mobile:tels[0]||'',phone:tels[1]||'',email:get('EMAIL'),website:get('URL'),address:get('ADR').replace(/;/g,' ').replace(/\s+/g,' ').trim(),notes:get('NOTE'),department:'',messenger:'',context:'',project:'',tags:[],followUpDate:'',favorite:false,photoData:'',ocrRawText:'',interactions:[],createdAt:nowIso(),updatedAt:nowIso()}}).filter(x=>x.name)}
async function importVcfFiles(files){let n=0;for(const f of files){for(const c of parseVcards(await f.text())){const dup=findDuplicate(c);await dbPut(dup?mergeContact(dup,c):c);n++}}await reload();closeDlg('toolsDialog');toast('已匯入 '+n+' 位聯絡人')}

function getMyCard(){try{return JSON.parse(localStorage.getItem(MY_CARD_KEY)||'{}')}catch(e){return{}}}
function setMyCard(c){localStorage.setItem(MY_CARD_KEY,JSON.stringify(c))}
function fillMyCard(){const c=getMyCard();$('myName').value=c.name||'';$('myCompany').value=c.company||'';$('myTitle').value=c.title||'';$('myMobile').value=c.mobile||'';$('myEmail').value=c.email||'';$('myWebsite').value=c.website||'';renderMyCard(c)}
function myCardFromForm(){return{name:$('myName').value.trim(),company:$('myCompany').value.trim(),title:$('myTitle').value.trim(),mobile:$('myMobile').value.trim(),email:$('myEmail').value.trim(),website:$('myWebsite').value.trim()}}
async function loadQrLib(){await loadScript('https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.min.js',()=>!!window.qrcode)}
async function renderMyCard(c){$('myCardInitials').textContent=initials(c.name||'我');$('myCardPreviewName').textContent=c.name||'設定你的名片';$('myCardPreviewMeta').textContent=[c.company,c.title].filter(Boolean).join(' · ')||'分享時不用再交換紙本名片';$('qrBox').innerHTML='<span>QR</span>';if(!c.name)return;try{await loadQrLib();const qr=qrcode(0,'M');qr.addData(vcard(c));qr.make();$('qrBox').innerHTML=qr.createImgTag(4,0)}catch(e){console.error(e)}}
async function saveMyCard(e){e.preventDefault();const c=myCardFromForm();setMyCard(c);await renderMyCard(c);toast('我的名片已儲存')}
async function shareMyCard(){const c=getMyCard();if(!c.name)return toast('先填姓名並儲存我的名片');await shareVcard(c)}

function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('這台瀏覽器暫不支援語音辨識');const r=new R();r.lang='zh-TW';r.interimResults=false;r.maxAlternatives=1;$('voiceNoteBtn').textContent='●';r.onresult=e=>{const t=e.results[0][0].transcript.trim();$('notes').value=[$('notes').value.trim(),t].filter(Boolean).join(' ')};r.onerror=()=>toast('語音辨識沒有成功');r.onend=()=>$('voiceNoteBtn').textContent='🎙';r.start()}
async function seedDemo(){const a=[{name:'陳怡君',company:'新北市政府',title:'科長',department:'交通規劃科',mobile:'0912-345-678',email:'yijun@example.gov.tw',context:'專案會議',project:'自行車路網',tags:['公部門','新北','自行車'],followUpDate:today(),favorite:true,notes:'關心轉乘節點與斷鏈改善。',interactions:[{id:uid(),date:today(),type:'會議',note:'討論汐科周邊轉乘與斷鏈改善方向。'}]},{name:'林志宏',company:'遠見工程顧問',title:'協理',mobile:'0933-222-111',email:'jhlin@example.com',context:'研討會',project:'交流道改善',tags:['顧問','道路'],favorite:false,notes:'後續可討論綜規合作。',interactions:[]},{name:'Amy Wang',company:'Urban Mobility Lab',title:'Project Manager',email:'amy@example.com',context:'論壇',tags:['國際','Mobility'],favorite:false,notes:'英文聯繫。',interactions:[]}];for(const d of a)await dbPut(Object.assign({id:uid(),photoData:'',phone:'',messenger:'',website:'',address:'',department:d.department||'',ocrRawText:'',createdAt:nowIso(),updatedAt:nowIso()},d));await reload();toast('已載入示範資料')}
function setFilter(f){activeFilter=f;document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));document.querySelectorAll('.nav-item[data-nav]').forEach(b=>b.classList.remove('active'));if(f==='all')document.querySelector('[data-nav="contacts"]')?.classList.add('active');if(f==='favorite')document.querySelector('[data-nav="favorites"]')?.classList.add('active');if(f==='followup')document.querySelector('[data-nav="followup"]')?.classList.add('active');render();window.scrollTo({top:0,behavior:'smooth'})}

function bind(){
 $('scanBtn').onclick=openScan;$('quickAddBtn').onclick=openQuick;$('emptyScanBtn').onclick=openScan;$('emptyAddBtn').onclick=openQuick;$('fabAdd').onclick=()=>openDlg('captureChoiceDialog');$('choiceScanBtn').onclick=openScan;$('choiceQuickBtn').onclick=openQuick;
 $('contactForm').addEventListener('submit',saveForm);$('deleteBtn').onclick=delCurrent;$('takePhotoBtn').onclick=()=>$('cameraInput').click();$('choosePhotoBtn').onclick=()=>$('photoInput').click();$('ocrBtn').onclick=runOCR;
 ['cameraInput','photoInput'].forEach(id=>$(id).addEventListener('change',async e=>{await readPhoto(e.target.files[0]);e.target.value=''}));$('removePhotoBtn').onclick=()=>{$('photoData').value='';$('ocrRawText').value='';$('photoPreview').innerHTML='<span class="photo-placeholder-icon">▣</span><span>拍一張名片，讓我幫你讀</span>';$('removePhotoBtn').classList.add('hidden');$('ocrBtn').classList.add('hidden');$('rawOcrDetails').classList.add('hidden')};
 $('voiceNoteBtn').onclick=startVoice;document.querySelectorAll('#contextSuggestions button').forEach(b=>b.onclick=()=>{$('context').value=b.dataset.context;$('advancedDetails').open=true;toast('已記為「'+b.dataset.context+'」')});
 document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>closeDlg(b.dataset.closeDialog));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
 $('contactsList').onclick=e=>{const c=e.target.closest('.contact-card');if(c)showDetail(c.dataset.id)};$('searchInput').oninput=()=>{$('searchInput').parentElement.classList.toggle('has-text',!!$('searchInput').value);render()};$('clearSearch').onclick=()=>{$('searchInput').value='';$('searchInput').parentElement.classList.remove('has-text');render();$('searchInput').focus()};$('sortSelect').onchange=render;
 document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));document.querySelectorAll('[data-jump-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.jumpFilter));document.querySelectorAll('.nav-item[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='contacts')setFilter('all');else if(n==='followup')setFilter('followup');else if(n==='favorites')setFilter('favorite');else if(n==='tools')openDlg('toolsDialog')});
 $('detailFavoriteBtn').onclick=toggleFavorite;$('detailEditBtn').onclick=editDetail;$('detailShareBtn').onclick=shareCurrent;$('calendarBtn').onclick=addCalendar;$('addInteractionBtn').onclick=()=>{$('interactionDate').value=today();$('interactionComposer').classList.remove('hidden')};$('cancelInteractionBtn').onclick=()=>$('interactionComposer').classList.add('hidden');$('saveInteractionBtn').onclick=saveInteraction;
 $('myCardBtn').onclick=()=>{fillMyCard();openDlg('myCardDialog')};$('myCardToolBtn').onclick=()=>{closeDlg('toolsDialog');fillMyCard();openDlg('myCardDialog')};$('myCardForm').onsubmit=saveMyCard;$('shareMyCardBtn').onclick=shareMyCard;
 $('backupBtn').onclick=backup;$('restoreBtn').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=async e=>{await restoreFile(e.target.files[0]);e.target.value=''};$('csvBtn').onclick=exportCsv;$('importVcfBtn').onclick=()=>$('vcfInput').click();$('vcfInput').onchange=async e=>{await importVcfFiles([...e.target.files]);e.target.value=''};$('seedDemoBtn').onclick=seedDemo
}
async function init(){try{db=await openDB();bind();await reload();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){console.error(e);alert('無法啟動本機資料庫，請確認瀏覽器允許網站儲存資料。')}}
init();
