const VERSION='0.7.0',SCHEMA_VERSION=3,DB_NAME='little-days-cards-db',STORE='contacts',INBOX_STORE='scanInbox',BATCH_STORE='importBatches',MY_CARD_KEY='little-days-cards-my-card',BACKUP_META_KEY='little-days-cards-backup-meta';
let db,contacts=[],activeFilter='all',activeCategory='',currentDetailId=null,currentMode='quick',ocrBusy=false,scanWorkerBusy=false,captureTarget='edit',restoreMode='merge',batchCaptured=0,importCandidates=[],importMappingNotes=[],importSourceFiles=[],aiFiles=[],pendingAiMeta=null;
const $=id=>document.getElementById(id);
const nowIso=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID?crypto.randomUUID():'c_'+Date.now()+'_'+Math.random().toString(36).slice(2);
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=(s='')=>String(s).toLowerCase().normalize('NFKC').trim();
const today=()=>new Date().toLocaleDateString('sv-SE');
const tags=v=>Array.isArray(v)?v:String(v||'').split(/[,，、|]/).map(x=>x.trim()).filter(Boolean);
const due=c=>!!c.followUpDate&&c.followUpDate<=today();
const recent=c=>Date.now()-new Date(c.createdAt||0).getTime()<30*864e5;
const phone=v=>'tel:'+String(v||'').replace(/[^\d+]/g,'');
const safeUrl=v=>/^https?:\/\//i.test(v||'')?v:'https://'+(v||'');
const interactions=c=>Array.isArray(c.interactions)?c.interactions:[];
const lastInteraction=c=>interactions(c).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0];

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,3);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'});if(!r.result.objectStoreNames.contains(INBOX_STORE))r.result.createObjectStore(INBOX_STORE,{keyPath:'id'});if(!r.result.objectStoreNames.contains(BATCH_STORE))r.result.createObjectStore(BATCH_STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const objectStore=(name,m='readonly')=>db.transaction(name,m).objectStore(name);
const store=(m='readonly')=>objectStore(STORE,m),inboxStore=(m='readonly')=>objectStore(INBOX_STORE,m),batchStore=(m='readonly')=>objectStore(BATCH_STORE,m);
const allFrom=s=>new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});
const putTo=(s,x)=>new Promise((res,rej)=>{const r=s.put(x);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const deleteFrom=(s,id)=>new Promise((res,rej)=>{const r=s.delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
const clearStore=s=>new Promise((res,rej)=>{const r=s.clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
const dbAll=()=>allFrom(store()),dbPut=x=>putTo(store('readwrite'),x),dbDelete=id=>deleteFrom(store('readwrite'),id),dbClear=()=>clearStore(store('readwrite'));
const inboxAll=()=>allFrom(inboxStore()),inboxPut=x=>putTo(inboxStore('readwrite'),x),inboxDelete=id=>deleteFrom(inboxStore('readwrite'),id),inboxClear=()=>clearStore(inboxStore('readwrite'));
const batchAll=()=>allFrom(batchStore()),batchPut=x=>putTo(batchStore('readwrite'),x),batchDelete=id=>deleteFrom(batchStore('readwrite'),id),batchClear=()=>clearStore(batchStore('readwrite'));
const inboxGet=id=>new Promise((res,rej)=>{const r=inboxStore().get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});
const batchGet=id=>new Promise((res,rej)=>{const r=batchStore().get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});

function initials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);return !p.length?'名':p.length>1?(p[0][0]+p[p.length-1][0]).toUpperCase():p[0].slice(0,2).toUpperCase()}
function fmtDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v+'T12:00:00'))}catch(e){return v}}
function daysUntil(v){if(!v)return null;return Math.round((new Date(v+'T00:00:00')-new Date(today()+'T00:00:00'))/864e5)}
function touchLabel(c){const i=lastInteraction(c);if(!i)return'';const d=daysUntil(i.date);if(d===0)return'今天互動';if(d===-1)return'昨天互動';if(d<0&&d>=-7)return Math.abs(d)+' 天前互動';return fmtDate(i.date)}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
function openDlg(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDlg(id){const d=$(id);if(d&&d.open)d.close()}

async function reload(){contacts=(await dbAll()).map(c=>Object.assign({},c,{interactions:interactions(c)}));render();await renderScanInbox()}
function categoryValues(c){return [...new Set([...(tags(c.tags)||[]),c.derived&&c.derived.organizationType,...((c.derived&&c.derived.domainTags)||[])].filter(Boolean))}
function matchesCategory(c,key){if(!key)return true;if(key.startsWith('company:'))return norm(c.company)===norm(key.slice(8));if(key.startsWith('tag:'))return categoryValues(c).some(v=>norm(v)===norm(key.slice(4)));return true}
function filtered(){const q=norm($('searchInput').value);let a=contacts.filter(c=>{if(activeFilter==='favorite'&&!c.favorite)return false;if(activeFilter==='followup'&&!due(c))return false;if(activeFilter==='recent'&&!recent(c))return false;if(!matchesCategory(c,activeCategory))return false;if(!q)return true;return norm([c.name,c.company,c.title,c.department,c.mobile,c.phone,c.email,c.messenger,c.website,c.address,c.context,c.project,c.notes,c.source&&c.source.app,c.source&&c.source.fileName,c.derived&&c.derived.organizationType].concat(tags(c.tags),c.derived&&c.derived.domainTags||[],interactions(c).flatMap(i=>[i.type,i.note,i.date])).join(' ')).includes(q)});const s=$('sortSelect').value;if(s==='created-desc')a.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));else if(s==='interaction-desc')a.sort((x,y)=>String((lastInteraction(y)||{}).date||'').localeCompare(String((lastInteraction(x)||{}).date||'')));else if(s==='name-asc')a.sort((x,y)=>String(x.name||'').localeCompare(String(y.name||''),'zh-Hant'));else if(s==='company-asc')a.sort((x,y)=>String(x.company||'').localeCompare(String(y.company||''),'zh-Hant'));else a.sort((x,y)=>new Date(y.updatedAt)-new Date(x.updatedAt));return a}
function alphaKey(name=''){const ch=String(name).trim().charAt(0).toUpperCase();return /^[A-Z]$/.test(ch)?ch:'#'}
function card(c){const ts=tags(c.tags).slice(0,2),hasPhoto=!!c.photoData,img=hasPhoto?'<img src="'+c.photoData+'" alt="'+esc(c.name)+'名片照片">':esc(initials(c.name)),meta=[c.company,c.title].filter(Boolean).join(' · ')||c.email||c.mobile||'尚未補充公司資訊',touch=touchLabel(c),needs=(c.aiMeta&&Array.isArray(c.aiMeta.needsConfirmation)&&c.aiMeta.needsConfirmation.length)||0;return '<button id="contact-'+esc(c.id)+'" class="contact-card compact-person" data-id="'+esc(c.id)+'" data-alpha="'+alphaKey(c.name)+'"><span class="avatar '+(hasPhoto?'card-thumb':'initial-thumb')+'">'+img+'</span><span class="contact-main"><strong>'+esc(c.name)+'</strong><span class="meta">'+esc(meta)+'</span>'+(ts.length?'<span class="tagline">'+ts.map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</span>':'')+'</span><span class="card-side">'+(needs?'<span class="ai-check-pill">需確認 '+needs+'</span>':'')+(c.favorite?'<span class="star">★</span>':'')+(due(c)?'<span class="followup-pill">待追蹤</span>':'')+(touch?'<span class="last-touch">'+esc(touch)+'</span>':'')+'<span>›</span></span></button>'}
function render(){const fav=contacts.filter(x=>x.favorite).length,dues=contacts.filter(due).length,intCount=contacts.reduce((n,c)=>n+interactions(c).length,0);$('totalCount').textContent=contacts.length;$('favoriteCount').textContent=fav;$('followupCount').textContent=dues;$('interactionCount').textContent=intCount;const categoryLabel=activeCategory?(activeCategory.startsWith('company:')?activeCategory.slice(8):activeCategory.slice(4)):'';$('listTitle').textContent=categoryLabel||{all:'所有人脈',favorite:'最愛人脈',followup:'待追蹤',recent:'最近新增'}[activeFilter];const a=filtered();$('contactsList').innerHTML=a.map(card).join('');$('emptyState').classList.toggle('hidden',contacts.length!==0||$('searchInput').value||activeFilter!=='all'||!!activeCategory);if(contacts.length&&!a.length)$('contactsList').innerHTML='<div class="empty-state"><div class="empty-icon">⌕</div><h3>找不到符合的人</h3><p>換個名字、公司、專案、場合或分類試試看。</p></div>';$('dueSpotlight').classList.toggle('hidden',!dues);if(dues)$('dueSpotlightText').textContent='有 '+dues+' 位人脈需要追蹤。';renderAlphabet(a);renderManagementHints()};
function mapHeaders(headers){const mapping={},used=[];headers.forEach((h,i)=>{const nh=normalizedHeader(h);for(const [field,aliases] of Object.entries(FIELD_ALIASES)){if(mapping[field]==null&&aliases.some(a=>normalizedHeader(a)===nh)){mapping[field]=i;used.push({field,header:String(h)});break}}});return{mapping,used}}
function parseCsvRows(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(q){if(ch==='"'&&next==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else if(ch==='"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell.replace(/\r$/,''));if(row.some(x=>String(x).trim()))rows.push(row);return rows}
function guessSourceApp(fileName=''){const n=fileName.toLowerCase();if(n.includes('camcard'))return'CamCard';if(/(^|[-_ ])eight/.test(n)||n.includes('8card'))return'Eight';if(n.includes('hihello'))return'HiHello';if(n.includes('sansan'))return'Sansan';if(n.includes('covve'))return'Covve';if(n.includes('contacts')||n.includes('contact'))return'聯絡人匯出';return'其他 App'}
function smartClassify(x){const text=norm([x.company,x.title,x.department,x.notes].join(' ')),domain=[];let org='其他';if(/政府|市府|縣府|公所|交通局|工務局|建設局|警察局|環保局|教育局|公路局|交通部|內政部|經濟部|署(?:\s|$)/.test(text))org='公部門';else if(/顧問|consult|工程/.test(text))org='工程顧問';else if(/建設|開發|營造|construction|developer/.test(text))org='建設／開發';else if(/大學|學院|研究院|university|college/.test(text))org='學術研究';else if(/銀行|bank|金融|證券/.test(text))org='金融';else if(x.company)org='企業';
 if(/交通|運輸|transport|traffic|mobility/.test(text))domain.push('交通運輸');if(/道路|公路|road|highway/.test(text))domain.push('道路');if(/停車|parking/.test(text))domain.push('停車');if(/自行車|bike|bicycle/.test(text))domain.push('自行車');if(/都市|urban|city planning/.test(text))domain.push('都市規劃');if(/捷運|軌道|metro|rail/.test(text))domain.push('軌道運輸');
 return{organizationType:org,domainTags:[...new Set(domain)],method:'local-smart-rules',generatedAt:nowIso()}}
function contactKey(x){if(x.email)return'e:'+norm(x.email);const m=String(x.mobile||'').replace(/\D/g,'');if(m.length>=8)return'm:'+m;if(x.name&&x.company)return'nc:'+norm(x.name)+'|'+norm(x.company);return''}
function normalizeImportedObject(raw,source={}){const o={},entries=Object.entries(raw||{}),headers=entries.map(([k])=>k),mh=mapHeaders(headers);for(const [field,idx] of Object.entries(mh.mapping)){const key=headers[idx];o[field]=raw[key]==null?'':String(raw[key]).trim()}if(!o.name&&raw.name)o.name=String(raw.name);if(!o.company&&raw.company)o.company=String(raw.company);if(!o.email&&raw.email)o.email=String(raw.email);if(!o.mobile&&raw.mobile)o.mobile=String(raw.mobile);return Object.assign({id:uid(),name:'',company:'',title:'',department:'',mobile:'',phone:'',email:'',messenger:'',website:'',address:'',context:'',project:'',tags:[],followUpDate:'',favorite:false,notes:'',photoData:'',ocrRawText:'',interactions:[],createdAt:nowIso(),updatedAt:nowIso()},o,{tags:tags(o.tags),source:Object.assign({kind:'file',importedAt:nowIso()},source)})}
function candidateStatus(contact,seen){if(!contact.name)return{status:'issue',reason:'缺少姓名'};const key=contactKey(contact);if(key&&seen.has(key))return{status:'duplicate',reason:'匯入檔內重複'};if(key)seen.add(key);const dup=findDuplicate(contact);if(dup)return{status:'duplicate',reason:'與現有人脈重複',duplicateId:dup.id};return{status:'ready',reason:'可直接匯入'}}
function rowsToCandidates(rows,source){if(!rows.length)return{items:[],mapping:[]};const headers=rows[0].map(x=>String(x||'').trim()),mh=mapHeaders(headers),seen=new Set(),items=[];for(const row of rows.slice(1)){if(!row.some(x=>String(x||'').trim()))continue;const raw={};headers.forEach((h,i)=>raw[h]=row[i]??'');const contact=normalizeImportedObject(raw,source),st=candidateStatus(contact,seen);contact.derived=smartClassify(contact);items.push({id:uid(),contact,...st,source})}return{items,mapping:mh.used}}
async function loadXlsx(){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>!!window.XLSX)}
async function parseImportFile(file){
 const ext=(file.name.split('.').pop()||'').toLowerCase(),source={fileName:file.name,app:guessSourceApp(file.name),kind:ext||file.type};
 if(file.type.startsWith('image/')){const item=await enqueuePhotoToInbox(file,{kind:'photo-import',app:'相簿匯入',fileName:file.name});return{photo:item?1:0,items:[],mapping:[]}}
 if(ext==='vcf'){const seen=new Set(),items=parseVcards(await file.text()).map(contact=>{contact.source=Object.assign({importedAt:nowIso()},source);contact.derived=smartClassify(contact);const st=candidateStatus(contact,seen);return{id:uid(),contact,...st,source}});return{items,mapping:[{field:'vCard',header:'標準 vCard 欄位'}]}}
 if(ext==='csv'||file.type.includes('csv'))return rowsToCandidates(parseCsvRows((await file.text()).replace(/^\uFEFF/,'')),source);
 if(ext==='xlsx'||ext==='xls'){await loadXlsx();const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),items=[],mapping=[];for(const name of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:false,defval:''});const out=rowsToCandidates(rows,Object.assign({},source,{sheet:name}));items.push(...out.items);mapping.push(...out.mapping)}return{items,mapping}}
 if(ext==='json'){const x=JSON.parse(await file.text()),arr=Array.isArray(x)?x:Array.isArray(x.contacts)?x.contacts:Array.isArray(x.data)?x.data:[];if(!arr.length)return{items:[{id:uid(),status:'issue',reason:'JSON 找不到聯絡人陣列',contact:{name:'JSON：'+file.name},source}],mapping:[]};const seen=new Set(),items=arr.map(raw=>{const contact=normalizeImportedObject(raw,source);if(raw.photoData)contact.photoData=raw.photoData;if(Array.isArray(raw.interactions))contact.interactions=raw.interactions;contact.derived=smartClassify(contact);const st=candidateStatus(contact,seen);return{id:uid(),contact,...st,source}});return{items,mapping:[]}}
 if(ext==='pdf')return{items:[{id:uid(),status:'issue',reason:'PDF 已接收；需 ChatGPT Vision 後端才能智慧拆分名片',contact:{name:'PDF：'+file.name},source}],mapping:[]};
 return{items:[{id:uid(),status:'issue',reason:'目前尚未支援這個檔案格式',contact:{name:file.name},source}],mapping:[]}
}
function renderImportPreview(){const sec=$('importPreviewSection');if(!sec)return;const total=importCandidates.length,ready=importCandidates.filter(x=>x.status==='ready').length,dups=importCandidates.filter(x=>x.status==='duplicate').length,issues=importCandidates.filter(x=>x.status==='issue').length;sec.classList.toggle('hidden',total===0);$('importTotalCount').textContent=total;$('importReadyCount').textContent=ready;$('importDuplicateCount').textContent=dups;$('importIssueCount').textContent=issues;$('importPreviewTitle').textContent=importSourceFiles.length>1?'多檔匯入預覽':(importSourceFiles[0]||'匯入預覽');const uniqueMap=[...new Map(importMappingNotes.map(x=>[(x.header||'')+'|'+x.field,x])).values()];const notice=$('mappingNotice');if(uniqueMap.length){notice.classList.remove('hidden');notice.innerHTML='<strong>智慧欄位對應</strong><span>'+uniqueMap.slice(0,12).map(x=>esc(x.header)+' → '+esc(x.field)).join('　')+(uniqueMap.length>12?'…':'')+'</span>'}else notice.classList.add('hidden');$('importCandidateList').innerHTML=importCandidates.slice(0,100).map(x=>'<article class="import-candidate '+esc(x.status)+'"><div class="candidate-avatar">'+esc(initials(x.contact.name||'?'))+'</div><div class="candidate-copy"><strong>'+esc(x.contact.name||'未命名資料')+'</strong><span>'+esc([x.contact.company,x.contact.title].filter(Boolean).join(' · ')||x.source.fileName||'')+'</span><small>'+esc((x.contact.derived&&[x.contact.derived.organizationType].concat(x.contact.derived.domainTags||[]).filter(Boolean).join('／'))||x.reason||'')+'</small></div><div class="candidate-status">'+(x.status==='ready'?'✓':x.status==='duplicate'?'重複':'!')+'</div></article>').join('');$('confirmImportBtn').disabled=ready===0;$('confirmImportBtn').textContent=ready?'匯入 '+ready+' 筆可用資料':'沒有可直接匯入的資料'}
async function processImportFiles(files){if(!files.length)return;resetImportPreview();importSourceFiles=files.map(f=>f.name);let photos=0;for(const file of files){try{const out=await parseImportFile(file);photos+=out.photo||0;importCandidates.push(...(out.items||[]));importMappingNotes.push(...(out.mapping||[]))}catch(e){console.error(e);importCandidates.push({id:uid(),status:'issue',reason:'檔案解析失敗',contact:{name:file.name},source:{fileName:file.name,app:guessSourceApp(file.name)}})}}renderImportPreview();if(photos){await renderScanInbox();toast('已把 '+photos+' 張照片送進待整理匣')}if(importCandidates.length)$('importPreviewSection').scrollIntoView({behavior:'smooth',block:'start'})}
async function confirmImport(){const ready=importCandidates.filter(x=>x.status==='ready');if(!ready.length)return;const batchId=uid(),createdIds=[];for(const item of ready){const contact=Object.assign({},item.contact,{id:item.contact.id||uid(),source:Object.assign({},item.contact.source,{importBatchId:batchId})});await dbPut(contact);createdIds.push(contact.id)}const batch={id:batchId,createdAt:nowIso(),files:[...importSourceFiles],count:createdIds.length,createdIds,status:'active'};await batchPut(batch);await reload();importCandidates=importCandidates.filter(x=>x.status!=='ready');renderImportPreview();await renderImportHistory();toast('已匯入 '+createdIds.length+' 位人脈')}
async function renderImportHistory(){if(!$('importHistoryList'))return;const batches=(await batchAll()).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,8);$('importHistoryList').innerHTML=batches.length?batches.map(b=>'<article class="import-history-item"><div><strong>'+esc((b.files||[]).join('、')||'匯入批次')+'</strong><span>'+esc(new Date(b.createdAt).toLocaleString('zh-TW'))+' · '+b.count+' 筆</span></div>'+(b.status==='active'?'<button data-rollback-batch="'+esc(b.id)+'">復原</button>':'<span class="rolled-back">已復原</span>')+'</article>').join(''):'<div class="timeline-empty">還沒有檔案匯入紀錄。</div>'}
async function rollbackImportBatch(id){const batch=await batchGet(id);if(!batch||batch.status!=='active')return;if(!confirm('要復原這次匯入的 '+batch.count+' 筆資料嗎？\n\n只會刪除這個批次新建立的人脈。'))return;for(const cid of batch.createdIds||[])await dbDelete(cid);batch.status='rolledback';batch.rolledBackAt=nowIso();await batchPut(batch);await reload();await renderImportHistory();toast('已復原這次匯入')}


function categoryStats(){const tagMap=new Map(),companyMap=new Map();for(const c of contacts){for(const v of categoryValues(c))tagMap.set(v,(tagMap.get(v)||0)+1);if(c.company)companyMap.set(c.company,(companyMap.get(c.company)||0)+1)}const sorter=(a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0]),'zh-Hant');return{tags:[...tagMap].sort(sorter),companies:[...companyMap].sort(sorter)}}
function openCategories(){closeDlg('toolsDialog');renderCategories();openDlg('categoryDialog')}
function renderCategories(){const s=categoryStats();$('categoryAllCount').textContent=contacts.length;$('categoryAllBtn').classList.toggle('active',!activeCategory);$('categoryList').innerHTML=s.tags.length?s.tags.map(([name,count])=>'<button class="category-row '+(activeCategory==='tag:'+name?'active':'')+'" data-category-key="tag:'+esc(name)+'"><span>'+esc(name)+'</span><b>'+count+'</b></button>').join(''):'<div class="timeline-empty">還沒有標籤或 AI 分類。</div>';$('companyCategoryList').innerHTML=s.companies.length?s.companies.slice(0,40).map(([name,count])=>'<button class="category-row '+(activeCategory==='company:'+name?'active':'')+'" data-category-key="company:'+esc(name)+'"><span>'+esc(name)+'</span><b>'+count+'</b></button>').join(''):'<div class="timeline-empty">還沒有公司資料。</div>'}
function selectCategory(key=''){activeCategory=key;activeFilter='all';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));closeDlg('categoryDialog');render();window.scrollTo({top:0,behavior:'smooth'})}
function renderAlphabet(list){const rail=$('alphabetRail');if(!rail)return;const keys=[...new Set(list.map(c=>alphaKey(c.name)))],order='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').filter(x=>keys.includes(x));if(keys.includes('#'))order.push('#');rail.innerHTML=order.map(k=>'<button data-alpha-jump="'+k+'">'+k+'</button>').join('');rail.classList.toggle('hidden',order.length<2)}
function jumpAlpha(k){$('sortSelect').value='name-asc';render();requestAnimationFrame(()=>{const el=document.querySelector('.contact-card[data-alpha="'+CSS.escape(k)+'"]');if(el)el.scrollIntoView({behavior:'smooth',block:'center'})})}
function duplicateGroups(){const maps={email:new Map(),mobile:new Map(),nameCompany:new Map()};for(const c of contacts){const e=norm(c.email),m=String(c.mobile||'').replace(/\D/g,''),nc=c.name&&c.company?norm(c.name)+'|'+norm(c.company):'';if(e){if(!maps.email.has(e))maps.email.set(e,[]);maps.email.get(e).push(c)}if(m.length>=8){if(!maps.mobile.has(m))maps.mobile.set(m,[]);maps.mobile.get(m).push(c)}if(nc){if(!maps.nameCompany.has(nc))maps.nameCompany.set(nc,[]);maps.nameCompany.get(nc).push(c)}}const seen=new Set(),groups=[];for(const map of Object.values(maps)){for(const arr of map.values()){if(arr.length<2)continue;const ids=arr.map(x=>x.id).sort(),key=ids.join('|');if(!seen.has(key)){seen.add(key);groups.push(arr)}}}return groups}
function isIncomplete(c){return !c.company||!(c.mobile||c.phone||c.email)}
function isStale(c){const last=lastInteraction(c),base=last&&last.date?new Date(last.date+'T12:00:00'):new Date(c.updatedAt||c.createdAt||0);return base.getTime()>0&&Date.now()-base.getTime()>365*864e5}
function healthData(){const confirm=contacts.filter(c=>c.aiMeta&&Array.isArray(c.aiMeta.needsConfirmation)&&c.aiMeta.needsConfirmation.length),incomplete=contacts.filter(isIncomplete),stale=contacts.filter(isStale),duplicates=duplicateGroups(),ids=new Set([...confirm,...incomplete,...stale].map(x=>x.id));duplicates.flat().forEach(x=>ids.add(x.id));return{confirm,incomplete,stale,duplicates,total:ids.size}}
function renderManagementHints(){const s=categoryStats(),h=healthData();if($('categoryHint'))$('categoryHint').textContent=(s.tags.length+s.companies.length)+' 個可用分類';if($('healthHint'))$('healthHint').textContent=h.total?h.total+' 位需要留意':'目前資料很乾淨';if($('healthBadge')){$('healthBadge').textContent=h.total;$('healthBadge').classList.toggle('hidden',!h.total)}}
function openHealth(){closeDlg('toolsDialog');renderHealth('all');openDlg('healthDialog')}
function healthSectionButton(type,label,count){return '<button data-health-type="'+type+'"><strong>'+count+'</strong><span>'+label+'</span></button>'}
function renderHealth(type='all'){const h=healthData();$('healthHeroTitle').textContent=h.total?'有 '+h.total+' 位值得看一下':'資料很乾淨';$('healthHeroText').textContent=h.total?'不用整理全部，只處理下面例外。':'目前沒有重複、缺資料或 AI 待確認。';$('healthSummary').innerHTML=healthSectionButton('confirm','AI 待確認',h.confirm.length)+healthSectionButton('duplicate','疑似重複',h.duplicates.length)+healthSectionButton('incomplete','資料不完整',h.incomplete.length)+healthSectionButton('stale','久未聯絡',h.stale.length);let items=[];if(type==='confirm'||type==='all')items.push(...h.confirm.map(c=>({c,label:'AI 待確認 '+(c.aiMeta.needsConfirmation||[]).join('、')})));if(type==='incomplete'||type==='all')items.push(...h.incomplete.map(c=>({c,label:!c.company?'缺公司資訊':'缺聯絡方式'})));if(type==='stale'||type==='all')items.push(...h.stale.map(c=>({c,label:'超過一年沒有更新／互動'})));if(type==='duplicate'||type==='all')h.duplicates.forEach(g=>items.push({group:g,label:'疑似同一人：'+g.map(x=>x.name).join(' / ')}));const seen=new Set();items=items.filter(x=>{const k=x.group?'g:'+x.group.map(y=>y.id).sort().join('|'):'c:'+x.c.id+'|'+x.label;if(seen.has(k))return false;seen.add(k);return true});$('healthDetailList').innerHTML=items.length?items.map(x=>x.group?'<article class="health-item duplicate"><span class="health-mark">≋</span><div><strong>'+esc(x.label)+'</strong><small>'+esc(x.group.map(y=>[y.company,y.email||y.mobile].filter(Boolean).join(' · ')).join('｜'))+'</small></div><button data-contact-id="'+esc(x.group[0].id)+'">查看</button></article>':'<article class="health-item"><span class="health-mark">!</span><div><strong>'+esc(x.c.name)+'</strong><small>'+esc(x.label)+' · '+esc(x.c.company||'未填公司')+'</small></div><button data-contact-id="'+esc(x.c.id)+'">查看</button></article>').join(''):'<div class="health-clean">✓ 這一類目前沒有需要處理的項目</div>'}

function getMyCard(){try{return JSON.parse(localStorage.getItem(MY_CARD_KEY)||'{}')}catch(e){return{}}}
function setMyCard(c){localStorage.setItem(MY_CARD_KEY,JSON.stringify(c))}
function fillMyCard(){const c=getMyCard();$('myName').value=c.name||'';$('myCompany').value=c.company||'';$('myTitle').value=c.title||'';$('myMobile').value=c.mobile||'';$('myEmail').value=c.email||'';$('myWebsite').value=c.website||'';renderMyCard(c)}
function myCardFromForm(){return{name:$('myName').value.trim(),company:$('myCompany').value.trim(),title:$('myTitle').value.trim(),mobile:$('myMobile').value.trim(),email:$('myEmail').value.trim(),website:$('myWebsite').value.trim()}}
async function loadQrLib(){await loadScript('https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.min.js',()=>!!window.qrcode)}
async function renderMyCard(c){$('myCardInitials').textContent=initials(c.name||'我');$('myCardPreviewName').textContent=c.name||'設定你的名片';$('myCardPreviewMeta').textContent=[c.company,c.title].filter(Boolean).join(' · ')||'分享時不用再交換紙本名片';$('qrBox').innerHTML='<span>QR</span>';if(!c.name)return;try{await loadQrLib();const qr=qrcode(0,'M');qr.addData(vcard(c));qr.make();$('qrBox').innerHTML=qr.createImgTag(4,0)}catch(e){console.error(e)}}
async function saveMyCard(e){e.preventDefault();const c=myCardFromForm();setMyCard(c);await renderMyCard(c);toast('我的名片已儲存')}
async function shareMyCard(){const c=getMyCard();if(!c.name)return toast('先填姓名並儲存我的名片');await shareVcard(c)}

function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('這台瀏覽器暫不支援語音辨識');const r=new R();r.lang='zh-TW';r.interimResults=false;r.maxAlternatives=1;$('voiceNoteBtn').textContent='●';r.onresult=e=>{const t=e.results[0][0].transcript.trim();$('notes').value=[$('notes').value.trim(),t].filter(Boolean).join(' ')};r.onerror=()=>toast('語音辨識沒有成功');r.onend=()=>$('voiceNoteBtn').textContent='🎙';r.start()}
async function seedDemo(){const a=[{name:'陳怡君',company:'新北市政府',title:'科長',department:'交通規劃科',mobile:'0912-345-678',email:'yijun@example.gov.tw',context:'專案會議',project:'自行車路網',tags:['公部門','新北','自行車'],followUpDate:today(),favorite:true,notes:'關心轉乘節點與斷鏈改善。',interactions:[{id:uid(),date:today(),type:'會議',note:'討論汐科周邊轉乘與斷鏈改善方向。'}]},{name:'林志宏',company:'遠見工程顧問',title:'協理',mobile:'0933-222-111',email:'jhlin@example.com',context:'研討會',project:'交流道改善',tags:['顧問','道路'],favorite:false,notes:'後續可討論綜規合作。',interactions:[]},{name:'Amy Wang',company:'Urban Mobility Lab',title:'Project Manager',email:'amy@example.com',context:'論壇',tags:['國際','Mobility'],favorite:false,notes:'英文聯繫。',interactions:[]}];for(const d of a)await dbPut(Object.assign({id:uid(),photoData:'',phone:'',messenger:'',website:'',address:'',department:d.department||'',ocrRawText:'',createdAt:nowIso(),updatedAt:nowIso()},d));await reload();toast('已載入示範資料')}
function setFilter(f){activeFilter=f;activeCategory='';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));document.querySelectorAll('.nav-item[data-nav]').forEach(b=>b.classList.remove('active'));if(f==='all')document.querySelector('[data-nav="contacts"]')?.classList.add('active');if(f==='favorite')document.querySelector('[data-nav="favorites"]')?.classList.add('active');if(f==='followup')document.querySelector('[data-nav="followup"]')?.classList.add('active');render();window.scrollTo({top:0,behavior:'smooth'})}

function bind(){
 $('aiAssistantBtn').onclick=openAiAssistant;$('quickAddBtn').onclick=openQuick;$('emptyScanBtn').onclick=openAiAssistant;$('emptyAddBtn').onclick=openQuick;$('fabAdd').onclick=()=>openDlg('captureChoiceDialog');$('choiceAiBtn').onclick=openAiAssistant;$('choiceScanBtn').onclick=openScan;$('choiceImportBtn').onclick=openImportCenter;$('choiceQuickBtn').onclick=openQuick;
 $('categoryBtn').onclick=openCategories;$('categoryManageBtn').onclick=openCategories;$('categoryToolBtn').onclick=openCategories;$('healthCheckBtn').onclick=openHealth;$('healthToolBtn').onclick=openHealth;$('categoryAllBtn').onclick=()=>selectCategory('');$('categoryList').onclick=e=>{const b=e.target.closest('[data-category-key]');if(b)selectCategory(b.dataset.categoryKey)};$('companyCategoryList').onclick=e=>{const b=e.target.closest('[data-category-key]');if(b)selectCategory(b.dataset.categoryKey)};$('alphabetRail').onclick=e=>{const b=e.target.closest('[data-alpha-jump]');if(b)jumpAlpha(b.dataset.alphaJump)};$('healthSummary').onclick=e=>{const b=e.target.closest('[data-health-type]');if(b)renderHealth(b.dataset.healthType)};$('healthDetailList').onclick=e=>{const b=e.target.closest('[data-contact-id]');if(b){closeDlg('healthDialog');showDetail(b.dataset.contactId)}};

 $('contactForm').addEventListener('submit',saveForm);$('deleteBtn').onclick=delCurrent;
 $('takePhotoBtn').onclick=()=>{captureTarget='edit';$('cameraInput').click()};$('choosePhotoBtn').onclick=()=>{captureTarget='edit';$('photoInput').click()};$('ocrBtn').onclick=runOCR;
 $('batchCameraBtn').onclick=()=>{captureTarget='batch';$('cameraInput').click()};$('batchAlbumBtn').onclick=()=>{captureTarget='batch';$('photoInput').click()};$('batchDoneBtn').onclick=()=>{closeDlg('scanBatchDialog');toast(batchCaptured?'已收下 '+batchCaptured+' 張，會繼續整理':'已完成')};
 $('cameraInput').addEventListener('change',async e=>{const file=e.target.files[0];if(captureTarget==='batch')await addScanToInbox(file);else await readPhoto(file);e.target.value='';captureTarget='edit'});
 $('photoInput').addEventListener('change',async e=>{const files=[...e.target.files];if(captureTarget==='batch'){for(const file of files)await addScanToInbox(file)}else if(captureTarget==='importphotos'){for(const file of files)await enqueuePhotoToInbox(file,{kind:'photo-import',app:'相簿匯入',fileName:file.name});await renderScanInbox();if(files.length)toast('已把 '+files.length+' 張照片送進待整理匣')}else if(files[0])await readPhoto(files[0]);e.target.value='';captureTarget='edit'});
 $('removePhotoBtn').onclick=()=>{$('photoData').value='';$('ocrRawText').value='';$('photoPreview').innerHTML='<span class="photo-placeholder-icon">▣</span><span>拍一張名片，讓我幫你讀</span>';$('removePhotoBtn').classList.add('hidden');$('ocrBtn').classList.add('hidden');$('rawOcrDetails').classList.add('hidden')};

 $('aiAttachBtn').onclick=()=>$('aiFilesInput').click();$('aiFilesInput').onchange=e=>{aiFiles=[...aiFiles,...e.target.files];renderAiFiles();e.target.value=''};$('aiAttachmentList').onclick=e=>{const b=e.target.closest('[data-remove-ai-file]');if(!b)return;aiFiles.splice(Number(b.dataset.removeAiFile),1);renderAiFiles()};$('aiFreeSendBtn').onclick=shareFreeAi;$('aiClipboardBtn').onclick=applyAiClipboard;$('aiResultFileBtn').onclick=()=>$('aiResultFileInput').click();$('aiResultFileInput').onchange=async e=>{await readAiResultFile(e.target.files[0]);e.target.value=''};$('aiApplyResultBtn').onclick=()=>applyAiPayloadText($('aiResultPaste').value);
 $('paidModeBtn').onclick=()=>{closeDlg('aiAssistantDialog');$('apiCostAck').checked=false;$('continueApiBtn').disabled=true;openDlg('apiCostDialog')};$('apiCostAck').onchange=e=>$('continueApiBtn').disabled=!e.target.checked;$('keepFreeBtn').onclick=()=>{closeDlg('apiCostDialog');openDlg('aiAssistantDialog')};$('continueApiBtn').onclick=()=>{if(!$('apiCostAck').checked)return;closeDlg('apiCostDialog');openDlg('apiSetupDialog')};$('backToFreeBtn').onclick=()=>{closeDlg('apiSetupDialog');openDlg('aiAssistantDialog')};

 $('importPhotosBtn').onclick=()=>{captureTarget='importphotos';$('photoInput').click()};$('importFilesBtn').onclick=()=>$('importFilesInput').click();$('importFilesInput').onchange=async e=>{await processImportFiles([...e.target.files]);e.target.value=''};
 $('clearImportPreviewBtn').onclick=resetImportPreview;$('cancelImportBtn').onclick=resetImportPreview;$('confirmImportBtn').onclick=confirmImport;$('importHistoryList').onclick=e=>{const b=e.target.closest('[data-rollback-batch]');if(b)rollbackImportBatch(b.dataset.rollbackBatch)};
 $('voiceNoteBtn').onclick=startVoice;document.querySelectorAll('#contextSuggestions button').forEach(b=>b.onclick=()=>{$('context').value=b.dataset.context;$('advancedDetails').open=true;toast('已記為「'+b.dataset.context+'」')});
 document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>closeDlg(b.dataset.closeDialog));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
 $('contactsList').onclick=e=>{const card=e.target.closest('.contact-card');if(card)showDetail(card.dataset.id)};$('scanInboxList').onclick=e=>{const card=e.target.closest('[data-scan-id]');if(card)reviewInboxItem(card.dataset.scanId)};
 $('searchInput').oninput=()=>{$('searchInput').parentElement.classList.toggle('has-text',!!$('searchInput').value);render()};$('clearSearch').onclick=()=>{$('searchInput').value='';$('searchInput').parentElement.classList.remove('has-text');render();$('searchInput').focus()};$('sortSelect').onchange=render;
 document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));document.querySelectorAll('[data-jump-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.jumpFilter));document.querySelectorAll('.nav-item[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='contacts')setFilter('all');else if(n==='followup')setFilter('followup');else if(n==='favorites')setFilter('favorite');else if(n==='tools')openDlg('toolsDialog')});
 $('detailFavoriteBtn').onclick=toggleFavorite;$('detailEditBtn').onclick=editDetail;$('detailShareBtn').onclick=shareCurrent;$('calendarBtn').onclick=addCalendar;$('addInteractionBtn').onclick=()=>{$('interactionDate').value=today();$('interactionComposer').classList.remove('hidden')};$('cancelInteractionBtn').onclick=()=>$('interactionComposer').classList.add('hidden');$('saveInteractionBtn').onclick=saveInteraction;
 $('myCardBtn').onclick=()=>{fillMyCard();openDlg('myCardDialog')};$('myCardToolBtn').onclick=()=>{closeDlg('toolsDialog');fillMyCard();openDlg('myCardDialog')};$('myCardForm').onsubmit=saveMyCard;$('shareMyCardBtn').onclick=shareMyCard;
 $('aiAssistantToolBtn').onclick=openAiAssistant;$('importCenterToolBtn').onclick=openImportCenter;$('backupBtn').onclick=openBackupCenter;$('openBackupCenterBtn').onclick=openBackupCenter;$('fullBackupBtn').onclick=backup;
 $('mergeRestoreBtn').onclick=()=>{restoreMode='merge';$('restoreInput').click()};$('replaceRestoreBtn').onclick=()=>{restoreMode='replace';$('restoreInput').click()};$('restoreInput').onchange=async e=>{await restoreFile(e.target.files[0],restoreMode);e.target.value=''};
 $('csvBtn').onclick=exportCsv;$('seedDemoBtn').onclick=seedDemo
}
async function init(){try{db=await openDB();bind();await reload();setTimeout(processScanQueue,700);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){console.error(e);alert('無法啟動本機資料庫，請確認瀏覽器允許網站儲存資料。')}}
init();
