const VERSION='0.10.0',SCHEMA_VERSION=3,DB_NAME='little-days-cards-db',STORE='contacts',INBOX_STORE='scanInbox',BATCH_STORE='importBatches',MY_CARD_KEY='little-days-cards-my-card',BACKUP_META_KEY='little-days-cards-backup-meta';
let db,contacts=[],activeFilter='all',activeCategory='',currentDetailId=null,currentMode='quick',ocrBusy=false,scanWorkerBusy=false,captureTarget='edit',restoreMode='merge',batchCaptured=0,importCandidates=[],importMappingNotes=[],importSourceFiles=[],aiFiles=[],aiPreparedImages=[],pendingAiMeta=null;
const $=id=>document.getElementById(id);
const nowIso=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID?crypto.randomUUID():'c_'+Date.now()+'_'+Math.random().toString(36).slice(2);
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=(s='')=>String(s).toLowerCase().normalize('NFKC').trim();
const today=()=>new Date().toLocaleDateString('sv-SE');
const tags=v=>Array.isArray(v)?v:String(v||'').split(/[,，、|]/).map(x=>x.trim()).filter(Boolean);
const due=c=>!!c.followUpDate&&c.followUpDate<=today();
const recent=c=>Date.now()-new Date(c.createdAt||0).getTime()<30*864e5;
const phone=v=>'tel:'+String(v||'').replace(/[^\d+]/g,'');
const safeUrl=v=>/^https?:\/\//i.test(v||'')?v:'https://'+(v||'');
const interactions=c=>Array.isArray(c.interactions)?c.interactions:[];
const lastInteraction=c=>interactions(c).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0];

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,3);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'});if(!r.result.objectStoreNames.contains(INBOX_STORE))r.result.createObjectStore(INBOX_STORE,{keyPath:'id'});if(!r.result.objectStoreNames.contains(BATCH_STORE))r.result.createObjectStore(BATCH_STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const objectStore=(name,m='readonly')=>db.transaction(name,m).objectStore(name);
const store=(m='readonly')=>objectStore(STORE,m),inboxStore=(m='readonly')=>objectStore(INBOX_STORE,m),batchStore=(m='readonly')=>objectStore(BATCH_STORE,m);
const allFrom=s=>new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});
const putTo=(s,x)=>new Promise((res,rej)=>{const r=s.put(x);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const deleteFrom=(s,id)=>new Promise((res,rej)=>{const r=s.delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
const clearStore=s=>new Promise((res,rej)=>{const r=s.clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
const dbAll=()=>allFrom(store()),dbPut=x=>putTo(store('readwrite'),x),dbDelete=id=>deleteFrom(store('readwrite'),id),dbClear=()=>clearStore(store('readwrite'));
const inboxAll=()=>allFrom(inboxStore()),inboxPut=x=>putTo(inboxStore('readwrite'),x),inboxDelete=id=>deleteFrom(inboxStore('readwrite'),id),inboxClear=()=>clearStore(inboxStore('readwrite'));
const batchAll=()=>allFrom(batchStore()),batchPut=x=>putTo(batchStore('readwrite'),x),batchDelete=id=>deleteFrom(batchStore('readwrite'),id),batchClear=()=>clearStore(batchStore('readwrite'));
const inboxGet=id=>new Promise((res,rej)=>{const r=inboxStore().get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});
const batchGet=id=>new Promise((res,rej)=>{const r=batchStore().get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});

function initials(name=''){const s=String(name||'').trim();return s?(s.charAt(0).toUpperCase()):'名'}
function fmtDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v+'T12:00:00'))}catch(e){return v}}
function daysUntil(v){if(!v)return null;return Math.round((new Date(v+'T00:00:00')-new Date(today()+'T00:00:00'))/864e5)}
function touchLabel(c){const i=lastInteraction(c);if(!i)return'';const d=daysUntil(i.date);if(d===0)return'今天互動';if(d===-1)return'昨天互動';if(d<0&&d>=-7)return Math.abs(d)+' 天前互動';return fmtDate(i.date)}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
function openDlg(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDlg(id){const d=$(id);if(d&&d.open)d.close()}

async function reload(){contacts=(await dbAll()).map(c=>Object.assign({},c,{interactions:interactions(c)}));render();await renderScanInbox()}
function categoryValues(c){return [...new Set([...(tags(c.tags)||[]),c.derived&&c.derived.organizationType,...((c.derived&&c.derived.domainTags)||[])].filter(Boolean))]}
function matchesCategory(c,key){if(!key)return true;if(key.startsWith('company:'))return norm(c.company)===norm(key.slice(8));if(key.startsWith('tag:'))return categoryValues(c).some(v=>norm(v)===norm(key.slice(4)));return true}
function filtered(){const q=norm($('searchInput').value);let a=contacts.filter(c=>{if(activeFilter==='favorite'&&!c.favorite)return false;if(activeFilter==='followup'&&!due(c))return false;if(activeFilter==='recent'&&!recent(c))return false;if(!matchesCategory(c,activeCategory))return false;if(!q)return true;return norm([c.name,c.company,c.title,c.department,c.mobile,c.phone,c.email,c.messenger,c.website,c.address,c.context,c.project,c.notes,c.source&&c.source.app,c.source&&c.source.fileName,c.derived&&c.derived.organizationType].concat(tags(c.tags),c.derived&&c.derived.domainTags||[],interactions(c).flatMap(i=>[i.type,i.note,i.date])).join(' ')).includes(q)});const s=$('sortSelect').value;if(s==='created-desc')a.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));else if(s==='interaction-desc')a.sort((x,y)=>String((lastInteraction(y)||{}).date||'').localeCompare(String((lastInteraction(x)||{}).date||'')));else if(s==='name-asc')a.sort((x,y)=>String(x.name||'').localeCompare(String(y.name||''),'zh-Hant'));else if(s==='company-asc')a.sort((x,y)=>String(x.company||'').localeCompare(String(y.company||''),'zh-Hant'));else a.sort((x,y)=>new Date(y.updatedAt)-new Date(x.updatedAt));return a}
function alphaKey(name=''){const ch=String(name).trim().charAt(0).toUpperCase();return /^[A-Z]$/.test(ch)?ch:'#'}
function card(c){const ts=tags(c.tags).slice(0,2),hasPhoto=!!c.photoData,img=hasPhoto?'<img src="'+c.photoData+'" alt="" aria-hidden="true">':esc((String(c.name||'名').trim().charAt(0)||'名')),meta=[c.company,c.title].filter(Boolean).join(' · ')||c.email||c.mobile||'尚未補充公司資訊',touch=touchLabel(c),needs=(c.aiMeta&&Array.isArray(c.aiMeta.needsConfirmation)&&c.aiMeta.needsConfirmation.length)||0;return '<button id="contact-'+esc(c.id)+'" class="contact-card compact-person" data-id="'+esc(c.id)+'" data-alpha="'+alphaKey(c.name)+'"><span class="avatar '+(hasPhoto?'card-thumb':'initial-thumb')+'">'+img+'</span><span class="contact-main"><strong>'+esc(c.name)+'</strong><span class="meta">'+esc(meta)+'</span>'+(ts.length?'<span class="tagline">'+ts.map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</span>':'')+'</span><span class="card-side">'+(needs?'<span class="ai-check-pill">需確認 '+needs+'</span>':'')+(c.favorite?'<span class="star">★</span>':'')+(due(c)?'<span class="followup-pill">待追蹤</span>':'')+(touch?'<span class="last-touch">'+esc(touch)+'</span>':'')+'<span>›</span></span></button>'}
function render(){const fav=contacts.filter(x=>x.favorite).length,dues=contacts.filter(due).length,intCount=contacts.reduce((n,c)=>n+interactions(c).length,0);$('totalCount').textContent=contacts.length;$('favoriteCount').textContent=fav;$('followupCount').textContent=dues;$('interactionCount').textContent=intCount;const a=filtered(),q=$('searchInput').value.trim(),categoryLabel=activeCategory?(activeCategory.startsWith('company:')?activeCategory.slice(8):activeCategory.slice(4)):'';$('listTitle').textContent=q?'搜尋結果 '+a.length+' / '+contacts.length:categoryLabel||{all:'所有人脈',favorite:'最愛人脈',followup:'待追蹤',recent:'最近新增'}[activeFilter];$('contactsList').innerHTML=a.map(card).join('');$('emptyState').classList.toggle('hidden',contacts.length!==0||q||activeFilter!=='all'||!!activeCategory);if(contacts.length&&!a.length)$('contactsList').innerHTML='<div class="empty-state"><div class="empty-icon">⌕</div><h3>找不到符合的人</h3><p>目前搜尋或分類條件沒有符合的人脈。清除搜尋即可回到全部 '+contacts.length+' 位。</p></div>';$('dueSpotlight').classList.toggle('hidden',!dues);if(dues)$('dueSpotlightText').textContent='有 '+dues+' 位人脈需要追蹤。';renderAlphabet(a);renderHomeCategories();renderManagementHints()}
function getBackupMeta(){try{return JSON.parse(localStorage.getItem(BACKUP_META_KEY)||'{}')}catch(e){return{}}}
function setBackupMeta(meta){localStorage.setItem(BACKUP_META_KEY,JSON.stringify(meta))}
function backupAgeText(iso){if(!iso)return'尚未建立完整備份';const days=Math.floor((Date.now()-new Date(iso).getTime())/864e5);if(days<=0)return'上次備份：今天';if(days===1)return'上次備份：昨天';return'上次備份：'+days+' 天前'}
function renderBackupStatus(items=[]){const meta=getBackupMeta(),text=backupAgeText(meta.lastBackupAt),el=$('backupSafetyText');if(el)el.textContent=text+(meta.contactCount!=null?' · '+meta.contactCount+' 筆人脈':'');if($('backupHeroMeta'))$('backupHeroMeta').textContent=text+(meta.fileName?' · '+meta.fileName:'');if($('backupPeopleCount'))$('backupPeopleCount').textContent=contacts.length;if($('backupPhotoCount'))$('backupPhotoCount').textContent=contacts.filter(x=>x.photoData).length+(items||[]).filter(x=>x.photoData).length;if($('backupPendingCount'))$('backupPendingCount').textContent=(items||[]).length}
function inboxLabel(x){if(x.status==='ready')return'已整理，點一下確認';if(x.status==='processing')return'正在背景整理…';if(x.status==='error')return'辨識不完整，點一下手動確認';return'已收下，等待整理'}
async function renderScanInbox(){const items=(await inboxAll()).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const panel=$('scanInboxPanel'),list=$('scanInboxList');if(!panel||!list)return;panel.classList.toggle('hidden',items.length===0);$('scanInboxCount').textContent=items.length;$('scanInboxStatus').textContent=items.some(x=>x.status==='processing')?'背景整理中':items.some(x=>x.status==='queued')?'等待整理':items.length?'請確認':'準備中';list.innerHTML=items.slice(0,12).map(x=>'<button class="inbox-card" data-scan-id="'+esc(x.id)+'"><span class="inbox-thumb">'+(x.photoData?'<img src="'+x.photoData+'" alt="待整理名片">':'▣')+'</span><span class="inbox-copy"><strong>'+esc((x.extracted&&x.extracted.name)||'待辨識名片')+'</strong><small>'+esc(inboxLabel(x))+'</small></span><span class="inbox-state '+esc(x.status||'queued')+'">'+(x.status==='ready'?'✓':x.status==='error'?'!':'…')+'</span></button>').join('');renderBackupStatus(items)}
function renderBatchState(){$('batchCount').textContent=batchCaptured;$('batchStatus').textContent=scanWorkerBusy?'背景整理中':'拍完可直接繼續下一張'}
async function reviewInboxItem(id){const item=await inboxGet(id);if(!item)return;resetForm();setMode('edit-scan');$('scanInboxId').value=item.id;$('photoData').value=item.photoData||'';$('originalPhotoData').value=item.originalPhotoData||item.photoData||'';$('ocrRawText').value=item.ocrRawText||'';if(item.photoData){$('photoPreview').innerHTML='<img src="'+item.photoData+'" alt="名片裁切照片">';$('removePhotoBtn').classList.remove('hidden');$('ocrBtn').classList.remove('hidden');$('photoPreserveStatus').classList.remove('hidden');$('photoPreserveStatus').innerHTML='<span>✓ 原始照片已保留</span><span>'+(item.cropMeta&&item.cropMeta.cropped?'✓ 已自動裁切名片':'• 使用原始照片')+'</span>'}const x=item.extracted||{};['name','company','title','department','mobile','phone','email','messenger','website','address'].forEach(k=>{if($(k)&&x[k])$(k).value=x[k]});if(item.ocrRawText){$('rawOcrText').textContent=item.ocrRawText;$('rawOcrDetails').classList.remove('hidden')}closeDlg('scanBatchDialog');openDlg('editDialog')}

function setMode(mode){currentMode=mode;const scan=mode==='scan'||mode==='edit-scan';$('scanPanel').classList.toggle('hidden',!scan);$('editEyebrow').textContent=scan?'SMART SCAN':'QUICK ADD';$('editTitle').textContent=mode.indexOf('edit')===0?'編輯名片':scan?'掃描名片':'快速新增';$('formIntro').querySelector('strong').textContent=scan?'辨識後只要確認幾個重點。':'只要確認幾個重點就能存。'}
function resetForm(){$('contactForm').reset();$('contactId').value='';$('scanInboxId').value='';$('photoData').value='';$('originalPhotoData').value='';$('ocrRawText').value='';$('photoPreview').innerHTML='<span class="photo-placeholder-icon">▣</span><span>拍一張名片，讓我幫你讀</span>';$('photoPreserveStatus').classList.add('hidden');$('removePhotoBtn').classList.add('hidden');$('ocrBtn').classList.add('hidden');$('ocrProgress').classList.add('hidden');$('rawOcrDetails').classList.add('hidden');$('deleteBtn').classList.add('hidden');$('advancedDetails').open=false}
function openQuick(){closeDlg('captureChoiceDialog');resetForm();setMode('quick');openDlg('editDialog')}
function openScan(){closeDlg('captureChoiceDialog');batchCaptured=0;renderBatchState();$('batchPhotoPreview').innerHTML='<span class="photo-placeholder-icon">▣</span><span>把名片放滿畫面，背景越乾淨越好</span>';openDlg('scanBatchDialog');setTimeout(warmOcr,120)}
function fillForm(c){resetForm();setMode(c.photoData?'edit-scan':'edit');$('contactId').value=c.id;$('deleteBtn').classList.remove('hidden');['name','company','title','department','mobile','phone','email','messenger','website','address','context','project','followUpDate','notes'].forEach(k=>$(k).value=c[k]||'');$('tags').value=tags(c.tags).join(', ');$('favorite').checked=!!c.favorite;$('photoData').value=c.photoData||'';$('originalPhotoData').value=c.originalPhotoData||c.photoData||'';$('ocrRawText').value=c.ocrRawText||'';if(c.photoData){$('photoPreview').innerHTML='<img src="'+c.photoData+'" alt="名片裁切照片">';$('photoPreserveStatus').classList.remove('hidden');$('photoPreserveStatus').innerHTML='<span>✓ 原始照片已保留</span><span>'+(c.originalPhotoData&&c.originalPhotoData!==c.photoData?'✓ 已保留裁切版':'• 使用原始照片')+'</span>';$('removePhotoBtn').classList.remove('hidden');$('ocrBtn').classList.remove('hidden')}if(c.ocrRawText){$('rawOcrText').textContent=c.ocrRawText;$('rawOcrDetails').classList.remove('hidden')}}
function formData(){const id=$('contactId').value||uid(),old=contacts.find(x=>x.id===id),get=k=>$(k).value.trim();return{id,name:get('name'),company:get('company'),title:get('title'),department:get('department'),mobile:get('mobile'),phone:get('phone'),email:get('email'),messenger:get('messenger'),website:get('website'),address:get('address'),context:get('context'),project:get('project'),tags:tags(get('tags')),followUpDate:get('followUpDate'),notes:get('notes'),favorite:$('favorite').checked,photoData:$('photoData').value,originalPhotoData:$('originalPhotoData').value||$('photoData').value,ocrRawText:$('ocrRawText').value,interactions:old?interactions(old):[],source:old?old.source:(pendingAiMeta&&pendingAiMeta.source)||undefined,derived:old?old.derived:(pendingAiMeta&&pendingAiMeta.derived)||undefined,aiMeta:old?old.aiMeta:(pendingAiMeta&&pendingAiMeta.aiMeta)||undefined,createdAt:old?old.createdAt:nowIso(),updatedAt:nowIso()}}
function findDuplicate(x){return contacts.find(c=>c.id!==x.id&&((x.email&&c.email&&norm(x.email)===norm(c.email))||(x.mobile&&c.mobile&&x.mobile.replace(/\D/g,'')===c.mobile.replace(/\D/g,''))||(x.name&&x.company&&norm(x.name)===norm(c.name)&&norm(x.company)===norm(c.company))))}
function mergeContact(a,b){const p=(x,y)=>x||y;return Object.assign({},a,{name:p(b.name,a.name),company:p(b.company,a.company),title:p(b.title,a.title),department:p(b.department,a.department),mobile:p(b.mobile,a.mobile),phone:p(b.phone,a.phone),email:p(b.email,a.email),messenger:p(b.messenger,a.messenger),website:p(b.website,a.website),address:p(b.address,a.address),context:p(b.context,a.context),project:p(b.project,a.project),tags:[...new Set(tags(a.tags).concat(tags(b.tags)))],followUpDate:p(b.followUpDate,a.followUpDate),notes:[a.notes,b.notes].filter(Boolean).filter((v,i,z)=>z.indexOf(v)===i).join('\n'),favorite:!!(a.favorite||b.favorite),photoData:p(b.photoData,a.photoData),originalPhotoData:p(b.originalPhotoData,a.originalPhotoData||a.photoData),ocrRawText:p(b.ocrRawText,a.ocrRawText),interactions:interactions(a).concat(interactions(b)).sort((x,y)=>String(y.date).localeCompare(String(x.date))),source:b.source||a.source,derived:b.derived||a.derived,updatedAt:nowIso()})}
async function saveForm(e){e.preventDefault();let x=formData();if(!x.name)return toast('至少要有姓名');const originalId=x.id,dup=findDuplicate(x),scanId=$('scanInboxId').value;let merged=false;if(x.aiMeta&&Array.isArray(x.aiMeta.needsConfirmation)&&x.aiMeta.needsConfirmation.length)x.aiMeta=Object.assign({},x.aiMeta,{needsConfirmation:[],confirmedAt:nowIso(),confirmedBy:'user'});if(dup&&confirm('看起來「'+dup.name+'」已經存在。\n\n要把這次資料合併到既有人脈嗎？')){x=mergeContact(dup,x);merged=true}await dbPut(x);if(merged&&originalId!==x.id)await dbDelete(originalId);if(scanId)await inboxDelete(scanId);closeDlg('editDialog');pendingAiMeta=null;await reload();processScanQueue();toast(merged?'已合併並儲存':'已快速儲存')}
async function delCurrent(){const id=$('contactId').value;if(!id||!confirm('確定要刪除這張名片嗎？'))return;await dbDelete(id);closeDlg('editDialog');closeDlg('detailDialog');await reload();toast('名片已刪除')}

function compress(file,max=1600,q=.86){return new Promise((res,rej)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight,s=Math.min(1,max/Math.max(w,h));w=Math.round(w*s);h=Math.round(h*s);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',q))};img.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('decode'))};img.src=u})}
function loadScript(src,test){return new Promise((res,rej)=>{if(test())return res();const existing=[...document.scripts].find(x=>x.src===src);if(existing){const t=setInterval(()=>{if(test()){clearInterval(t);res()}},80);setTimeout(()=>{clearInterval(t);test()?res():rej(new Error('load timeout'))},12000);return}const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>test()?res():setTimeout(()=>test()?res():rej(new Error('load')),250);s.onerror=rej;document.head.appendChild(s)})}
function dataUrlCanvas(dataUrl,max=1600){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>{const s=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*s));c.height=Math.max(1,Math.round(img.naturalHeight*s));c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c)};img.onerror=rej;img.src=dataUrl})}
async function fastAutoCropCard(dataUrl){const src=await dataUrlCanvas(dataUrl,1600),dw=Math.min(360,src.width),dh=Math.max(1,Math.round(src.height*dw/src.width)),mini=document.createElement('canvas');mini.width=dw;mini.height=dh;const mctx=mini.getContext('2d',{willReadFrequently:true});mctx.drawImage(src,0,0,dw,dh);const im=mctx.getImageData(0,0,dw,dh),d=im.data,xScore=new Float32Array(dw),yScore=new Float32Array(dh);for(let y=1;y<dh-1;y++){let row=0;for(let x=1;x<dw-1;x++){const i=(y*dw+x)*4,l=i-4,r=i+4,u=i-dw*4,b=i+dw*4,gx=Math.abs((d[r]+d[r+1]+d[r+2])-(d[l]+d[l+1]+d[l+2])),gy=Math.abs((d[b]+d[b+1]+d[b+2])-(d[u]+d[u+1]+d[u+2])),g=gx+gy;xScore[x]+=g;row+=g}yScore[y]=row}
 const pick=(arr,a,b)=>{let bi=a,bv=-1;for(let i=a;i<b;i++){const v=(arr[i-2]||0)+(arr[i-1]||0)+arr[i]+(arr[i+1]||0)+(arr[i+2]||0);if(v>bv){bv=v;bi=i}}return bi},left=pick(xScore,Math.floor(dw*.03),Math.floor(dw*.46)),right=pick(xScore,Math.floor(dw*.54),Math.floor(dw*.97)),top=pick(yScore,Math.floor(dh*.03),Math.floor(dh*.46)),bottom=pick(yScore,Math.floor(dh*.54),Math.floor(dh*.97)),w=right-left,h=bottom-top,ratio=w/Math.max(1,h),area=(w*h)/(dw*dh);
 if(area<.24||ratio<1.25||ratio>2.25||w<dw*.42||h<dh*.28)return{dataUrl,cropped:false};
 const padX=Math.round(w*.018),padY=Math.round(h*.028),sx=Math.max(0,left-padX),sy=Math.max(0,top-padY),sw=Math.min(dw-sx,w+padX*2),sh=Math.min(dh-sy,h+padY*2),scaleX=src.width/dw,scaleY=src.height/dh,out=document.createElement('canvas');out.width=Math.round(sw*scaleX);out.height=Math.round(sh*scaleY);out.getContext('2d').drawImage(src,Math.round(sx*scaleX),Math.round(sy*scaleY),Math.round(sw*scaleX),Math.round(sh*scaleY),0,0,out.width,out.height);return{dataUrl:out.toDataURL('image/jpeg',.9),cropped:true}}
async function enhanceForOcr(dataUrl){const c=await dataUrlCanvas(dataUrl,1800),ctx=c.getContext('2d',{willReadFrequently:true}),target=1500;if(c.width<target){const ratio=target/c.width,out=document.createElement('canvas');out.width=target;out.height=Math.round(c.height*ratio);out.getContext('2d').drawImage(c,0,0,out.width,out.height);return enhanceCanvas(out)}return enhanceCanvas(c)}
function enhanceCanvas(c){const ctx=c.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const g=.299*d[i]+.587*d[i+1]+.114*d[i+2],v=Math.max(0,Math.min(255,(g-128)*1.18+134));d[i]=d[i+1]=d[i+2]=v}ctx.putImageData(im,0,0);return c.toDataURL('image/jpeg',.92)}
function warmOcr(){if(window.Tesseract)return;loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',()=>!!window.Tesseract).catch(()=>{})}
async function readPhoto(file){if(!file)return;if(file.size>20*1024*1024)return toast('圖片太大，請選較小的照片');try{const original=await compress(file);$('originalPhotoData').value=original;$('photoData').value=original;$('photoPreview').innerHTML='<img src="'+original+'" alt="名片照片預覽">';$('removePhotoBtn').classList.remove('hidden');$('ocrBtn').classList.remove('hidden');setOcrProgress(.08,'原始照片已保留，正在裁切名片…');await new Promise(r=>setTimeout(r,20));const crop=await fastAutoCropCard(original).catch(()=>({dataUrl:original,cropped:false})),d=crop.dataUrl;$('photoData').value=d;$('photoPreview').innerHTML='<img src="'+d+'" alt="名片裁切預覽">';$('photoPreserveStatus').classList.remove('hidden');$('photoPreserveStatus').innerHTML='<span>✓ 原始照片已保留</span><span>'+(crop.cropped?'✓ 已自動裁切名片':'• 未偵測到明確邊界，先保留原圖')+'</span>';$('ocrProgress').classList.add('hidden');toast(crop.cropped?'原圖已保留，名片也已自動裁切':'原圖已保留，這張先使用原始照片');if(currentMode==='scan')setTimeout(runOCR,80)}catch(e){console.error(e);$('ocrProgress').classList.add('hidden');toast('照片讀取失敗')}}
function setOcrProgress(p,text){$('ocrProgress').classList.remove('hidden');$('ocrProgressBar').style.width=Math.max(3,Math.round(p*100))+'%';$('ocrProgressText').textContent=text||'辨識中…'}
function ocrScore(raw){let s=0;if(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i.test(raw))s+=5;if(/(?:\+?\d[\d\s().-]{7,}\d)/.test(raw))s+=4;if(/[\u3400-\u9fff]{2,}/.test(raw))s+=3;if(/(公司|有限公司|Inc\.?|Ltd\.?|Corp\.?|Group|Manager|經理|工程師|主任|科長)/i.test(raw))s+=2;s+=Math.min(4,raw.split(/\r?\n/).filter(x=>x.trim().length>1).length/3);return s}
function parseBusinessCard(raw){const lines=raw.split(/\r?\n/).map(x=>x.replace(/[|｜]/g,' ').replace(/\s+/g,' ').trim()).filter(x=>x.length>1),joined=lines.join(' '),email=(joined.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'',urls=joined.match(/(?:https?:\/\/|www\.)[^\s]+/ig)||[],website=urls.find(x=>!x.includes('@'))||'',pm=joined.match(/(?:\+?\d[\d\s().-]{7,}\d)/g)||[],phones=[...new Set(pm.map(x=>x.trim()).filter(x=>x.replace(/\D/g,'').length>=8))],mobile=phones.find(x=>/09\d{8}|9\d{8}/.test(x.replace(/\D/g,'')))||phones[0]||'',phone2=phones.find(x=>x!==mobile)||'',companyRx=/(股份有限公司|有限公司|公司|集團|基金會|協會|公會|局|處|部|中心|研究院|工程顧問|科技|建設|銀行|醫院|大學|Inc\.?|Ltd\.?|Corp\.?|Company|Group|Consult)/i,titleRx=/(董事長|總經理|副總|協理|經理|副理|處長|科長|組長|主任|工程師|顧問|專員|教授|Project Manager|Product Manager|Manager|Director|Engineer|Consultant|President|CEO|CTO|CFO|VP)/i,addressRx=/(台灣|臺灣|台北|臺北|新北|桃園|新竹|台中|臺中|彰化|嘉義|台南|臺南|高雄|宜蘭|花蓮|市|縣|區|鄉|鎮|路|街|巷|號|Taiwan|Taipei|Taoyuan|Hsinchu|Taichung|Kaohsiung)/i,company=lines.find(x=>companyRx.test(x))||'',title=lines.find(x=>titleRx.test(x)&&x!==company)||'',address=lines.find(x=>addressRx.test(x)&&/\d/.test(x)&&x!==mobile&&x!==phone2)||'';let name=lines.find(x=>/^[\u3400-\u9fff·]{2,5}$/.test(x)&&!companyRx.test(x)&&!titleRx.test(x));if(!name)name=lines.find(x=>/^[A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,2}$/.test(x));if(!name)name=lines.find(x=>x.length>=2&&x.length<=18&&!/[\d@]/.test(x)&&!companyRx.test(x)&&!titleRx.test(x)&&!addressRx.test(x))||'';return{name,company,title,mobile,phone:phone2,email,website:website.replace(/[),.;]+$/,''),address}}
function applyOcrFields(x){Object.entries(x).forEach(([k,v])=>{if(v&&$(k)&&!$(k).value.trim())$(k).value=v});if(x.title||x.website||x.address)$('advancedDetails').open=true}
async function recognizeCardImage(dataUrl,onProgress){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',()=>!!window.Tesseract);const preview=await dataUrlCanvas(dataUrl,1250),ocrImage=preview.toDataURL('image/jpeg',.88),r=await Tesseract.recognize(ocrImage,'chi_tra+eng',{logger:m=>{if(onProgress&&m.status==='recognizing text')onProgress(m.progress||0)}}),raw=(r.data&&r.data.text?r.data.text:'').trim(),confidence=(r.data&&Number.isFinite(r.data.confidence)?r.data.confidence:0);return{raw,confidence,fields:parseBusinessCard(raw)}}
async function runOCR(){if(ocrBusy||!$('photoData').value)return;ocrBusy=true;$('ocrBtn').disabled=true;setOcrProgress(.08,'快速辨識中…');try{const out=await recognizeCardImage($('photoData').value,p=>setOcrProgress(.12+p*.84,'辨識 '+Math.round(p*100)+'%'));$('ocrRawText').value=out.raw;$('rawOcrText').textContent=out.raw;$('rawOcrDetails').classList.toggle('hidden',!out.raw);applyOcrFields(out.fields);setOcrProgress(1,'完成');toast(out.confidence>=60?'名片辨識完成':'已先填入可辨識資料，低信心欄位請快速確認')}catch(e){console.error(e);toast('辨識暫時失敗，照片已保留，可直接手動補資料')}finally{ocrBusy=false;$('ocrBtn').disabled=false;setTimeout(()=>$('ocrProgress').classList.add('hidden'),1000)}}
async function enqueuePhotoToInbox(file,source={kind:'photo',app:'相簿'}){if(!file)return null;if(file.size>20*1024*1024){toast('圖片太大，請選較小的照片');return null}try{const d=await compress(file,1600,.86),item={id:uid(),originalPhotoData:d,photoData:d,cropMeta:{cropped:false},ocrRawText:'',extracted:{},status:'queued',source:Object.assign({fileName:file.name||'',importedAt:nowIso()},source),createdAt:nowIso(),updatedAt:nowIso()};await inboxPut(item);await renderScanInbox();setTimeout(processScanQueue,120);return item}catch(e){console.error(e);toast('這張照片沒有成功收下，請再試一次');return null}}
async function addScanToInbox(file){const item=await enqueuePhotoToInbox(file,{kind:'camera',app:'現場拍照'});if(!item)return;batchCaptured++;$('batchPhotoPreview').innerHTML='<img src="'+item.photoData+'" alt="剛收下的名片">';renderBatchState();toast('已收下第 '+batchCaptured+' 張，可直接繼續拍')}
async function processScanQueue(){if(scanWorkerBusy)return;scanWorkerBusy=true;renderBatchState();try{while(true){const items=await inboxAll(),item=items.find(x=>x.status==='queued'||(x.status==='processing'&&Date.now()-new Date(x.updatedAt||x.createdAt).getTime()>120000));if(!item)break;item.status='processing';item.updatedAt=nowIso();await inboxPut(item);await renderScanInbox();try{const original=item.originalPhotoData||item.photoData,crop=await fastAutoCropCard(original).catch(()=>({dataUrl:original,cropped:false}));item.originalPhotoData=original;item.photoData=crop.dataUrl;item.cropMeta={cropped:!!crop.cropped,processedAt:nowIso()};const out=await recognizeCardImage(item.photoData);item.ocrRawText=out.raw;item.extracted=out.fields;item.confidence=out.confidence;item.status='ready';item.updatedAt=nowIso()}catch(e){console.error(e);item.status='error';item.error='ocr';item.updatedAt=nowIso()}await inboxPut(item);await renderScanInbox()}}finally{scanWorkerBusy=false;renderBatchState();await renderScanInbox()}}
function showDetail(id){const c=contacts.find(x=>x.id===id);if(!c)return;currentDetailId=id;$('detailName').textContent=c.name;const photo=c.photoData?'<div class="detail-photo-wrap"><div class="detail-photo-label">名片裁切版</div><img class="detail-photo" src="'+c.photoData+'" alt=""></div>':'',originalPhoto=c.originalPhotoData&&c.originalPhotoData!==c.photoData?'<details class="original-photo-details"><summary>查看保留的原始照片</summary><img src="'+c.originalPhotoData+'" alt=""></details>':'',ts=tags(c.tags),acts=[];if(c.mobile||c.phone)acts.push('<a class="action-button" href="'+phone(c.mobile||c.phone)+'">撥電話</a>');if(c.email)acts.push('<a class="action-button" href="mailto:'+encodeURIComponent(c.email)+'">寄 Email</a>');if(c.address)acts.push('<a class="action-button" target="_blank" rel="noopener" href="https://maps.apple.com/?q='+encodeURIComponent(c.address)+'">開地圖</a>');const rows=[],add=(l,v,h)=>{if(v)rows.push('<div class="info-row"><span>'+l+'</span><span>'+(h||esc(v))+'</span></div>')};add('公司',c.company);add('職稱',[c.department,c.title].filter(Boolean).join(' / '));add('手機',c.mobile,c.mobile?'<a href="'+phone(c.mobile)+'">'+esc(c.mobile)+'</a>':'');add('電話',c.phone,c.phone?'<a href="'+phone(c.phone)+'">'+esc(c.phone)+'</a>':'');add('Email',c.email,c.email?'<a href="mailto:'+encodeURIComponent(c.email)+'">'+esc(c.email)+'</a>':'');add('通訊',c.messenger);add('網站',c.website,c.website?'<a target="_blank" rel="noopener" href="'+esc(safeUrl(c.website))+'">'+esc(c.website)+'</a>':'');add('地址',c.address);add('場合',c.context);add('專案',c.project);add('追蹤',c.followUpDate,fmtDate(c.followUpDate));add('來源',c.source&&[c.source.app,c.source.fileName].filter(Boolean).join(' · '));add('分類',c.derived&&[c.derived.organizationType].concat(c.derived.domainTags||[]).filter(Boolean).join('、'));$('detailContent').innerHTML=photo+originalPhoto+'<div class="detail-meta"><h3>'+esc(c.name)+'</h3><p>'+esc([c.company,c.title].filter(Boolean).join(' · '))+'</p>'+(ts.length?'<div class="tagline">'+ts.map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</div>':'')+'</div>'+(acts.length?'<div class="action-grid">'+acts.join('')+'</div>':'')+'<div class="info-list">'+rows.join('')+'</div>'+(c.notes?'<div class="notes-card">'+esc(c.notes)+'</div>':'');$('detailFavoriteBtn').textContent=c.favorite?'★ 已加入最愛':'☆ 加入最愛';$('interactionComposer').classList.add('hidden');const pending=c.aiMeta&&Array.isArray(c.aiMeta.needsConfirmation)?c.aiMeta.needsConfirmation:[];$('detailAiConfirmBar').classList.toggle('hidden',!pending.length);$('detailAiConfirmText').textContent=pending.length?'待確認：'+pending.join('、')+'。確認後首頁提醒會更新。':'已確認';renderTimeline(c);openDlg('detailDialog')}
async function confirmAiContact(){const c=contacts.find(x=>x.id===currentDetailId);if(!c||!c.aiMeta)return;c.aiMeta=Object.assign({},c.aiMeta,{needsConfirmation:[],confirmedAt:nowIso(),confirmedBy:'user'});c.updatedAt=nowIso();await dbPut(c);await reload();$('detailAiConfirmBar').classList.add('hidden');toast('已確認，AI 提醒已清除')}
async function confirmAiContactById(id){const c=contacts.find(x=>x.id===id);if(!c||!c.aiMeta)return;c.aiMeta=Object.assign({},c.aiMeta,{needsConfirmation:[],confirmedAt:nowIso(),confirmedBy:'user'});c.updatedAt=nowIso();await dbPut(c);await reload();renderHealth('all');toast('已確認無誤，紅點已更新')}
function renderTimeline(c){const a=interactions(c).slice().sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));$('timelineList').innerHTML=a.length?a.map(i=>'<article class="timeline-item"><strong>'+esc(i.type||'互動')+'</strong><span>'+esc(fmtDate(i.date))+'</span><p>'+esc(i.note||'')+'</p></article>').join(''):'<div class="timeline-empty">還沒有互動紀錄。下一次聯絡後記一句，就不會忘記談過什麼。</div>'}
async function toggleFavorite(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;c.favorite=!c.favorite;c.updatedAt=nowIso();await dbPut(c);await reload();$('detailFavoriteBtn').textContent=c.favorite?'★ 已加入最愛':'☆ 加入最愛';toast(c.favorite?'已加入最愛':'已移除最愛')}
function editDetail(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;closeDlg('detailDialog');fillForm(c);openDlg('editDialog')}
async function saveInteraction(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;const note=$('interactionNote').value.trim();if(!note)return toast('寫一句這次互動的重點');c.interactions=interactions(c).concat([{id:uid(),date:$('interactionDate').value||today(),type:$('interactionType').value,note,createdAt:nowIso()}]);c.updatedAt=nowIso();await dbPut(c);await reload();renderTimeline(c);$('interactionNote').value='';$('interactionComposer').classList.add('hidden');toast('互動已記下')}

function vcard(c){return ['BEGIN:VCARD','VERSION:3.0','FN:'+(c.name||''),c.company?'ORG:'+c.company:'',c.title?'TITLE:'+c.title:'',c.mobile?'TEL;TYPE=CELL:'+c.mobile:'',c.phone?'TEL;TYPE=WORK:'+c.phone:'',c.email?'EMAIL:'+c.email:'',c.website?'URL:'+safeUrl(c.website):'',c.address?'ADR;TYPE=WORK:;;'+c.address+';;;;':'',c.notes?'NOTE:'+c.notes.replace(/\n/g,'\\n'):'','END:VCARD'].filter(Boolean).join('\r\n')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},900)}
async function shareVcard(c){const blob=new Blob([vcard(c)],{type:'text/vcard'}),file=new File([blob],(c.name||'contact')+'.vcf',{type:'text/vcard'});try{if(navigator.canShare&&navigator.canShare({files:[file]}))await navigator.share({title:c.name,text:[c.company,c.title].filter(Boolean).join(' · '),files:[file]});else download(blob,file.name)}catch(e){if(e.name!=='AbortError')toast('分享失敗')}}
async function shareCurrent(){const c=contacts.find(x=>x.id===currentDetailId);if(c)await shareVcard(c)}
function addCalendar(){const c=contacts.find(x=>x.id===currentDetailId);if(!c)return;if(!c.followUpDate)return toast('先在「編輯」設定下次追蹤日期');const d=c.followUpDate.replace(/-/g,''),next=new Date(c.followUpDate+'T00:00:00');next.setDate(next.getDate()+1);const de=next.toLocaleDateString('sv-SE').replace(/-/g,''),ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Little Days//Cards//ZH-TW','BEGIN:VEVENT','UID:'+uid()+'@little-days','DTSTART;VALUE=DATE:'+d,'DTEND;VALUE=DATE:'+de,'SUMMARY:追蹤 '+c.name,'DESCRIPTION:'+(c.notes||'與 '+c.name+' 聯絡').replace(/\n/g,'\\n'),'END:VEVENT','END:VCALENDAR'].join('\r\n');download(new Blob([ics],{type:'text/calendar'}),'追蹤_'+c.name+'_'+c.followUpDate+'.ics');toast('已建立行事曆事件檔')}

async function buildBackupPayload(){return{app:'little-days-cards',version:VERSION,schemaVersion:SCHEMA_VERSION,exportedAt:nowIso(),myCard:getMyCard(),settings:{activeFilter,sort:$('sortSelect')?$('sortSelect').value:'updated-desc'},contacts,scanInbox:await inboxAll(),importBatches:await batchAll()}}
async function emitBackup({share=true,prefix='人脈名片完整備份',record=true}={}){const x=await buildBackupPayload(),fileName=prefix+'_'+today()+'.json',blob=new Blob([JSON.stringify(x,null,2)],{type:'application/json'}),file=new File([blob],fileName,{type:'application/json'});let completed=false;try{if(share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:'人脈名片備份',text:'建議儲存到 iCloud Drive／Google Drive',files:[file]});completed=true}else{download(blob,fileName);completed=true}}catch(e){if(e.name!=='AbortError'){download(blob,fileName);completed=true}}if(completed&&record){setBackupMeta({lastBackupAt:nowIso(),fileName,contactCount:contacts.length,photoCount:contacts.filter(x=>x.photoData).length,inboxCount:x.scanInbox.length,schemaVersion:SCHEMA_VERSION});renderBackupStatus(x.scanInbox);toast('完整備份已建立')}return completed}
async function backup(){return emitBackup({share:true})}
async function openBackupCenter(){const items=await inboxAll();renderBackupStatus(items);closeDlg('toolsDialog');openDlg('backupDialog')}
async function restoreFile(file,mode=restoreMode){if(!file)return;try{const x=JSON.parse(await file.text());if(x.app&&x.app!=='little-days-cards')throw new Error('app');if(!Array.isArray(x.contacts))throw new Error('contacts');if(mode==='replace'){if(!confirm('整份取代會先下載一份「恢復前備份」，再清除目前資料。\n\n確定繼續嗎？'))return;await emitBackup({share:false,prefix:'恢復前備份',record:false});await dbClear();await inboxClear();await batchClear()}for(const raw of x.contacts){const contact=Object.assign({},raw,{id:raw.id||uid(),interactions:interactions(raw),createdAt:raw.createdAt||nowIso(),updatedAt:raw.updatedAt||nowIso()});if(mode==='merge'){const dup=findDuplicate(contact);await dbPut(dup?mergeContact(dup,contact):contact)}else await dbPut(contact)}if(Array.isArray(x.scanInbox)){for(const item of x.scanInbox)await inboxPut(Object.assign({},item,{id:item.id||uid(),status:item.status==='processing'?'queued':(item.status||'queued'),createdAt:item.createdAt||nowIso(),updatedAt:nowIso()}))}if(Array.isArray(x.importBatches)){for(const b of x.importBatches)await batchPut(b)}if(x.myCard)localStorage.setItem(MY_CARD_KEY,JSON.stringify(x.myCard));await reload();closeDlg('backupDialog');toast(mode==='replace'?'已完整恢復備份':'已合併恢復 '+x.contacts.length+' 筆');setTimeout(processScanQueue,500)}catch(e){console.error(e);alert('這不是有效的人脈名片備份檔，或檔案內容已損壞。')}}
const csvCell=v=>'"'+(Array.isArray(v)?v.join('|'):String(v==null?'':v)).replace(/"/g,'""')+'"';
function exportCsv(){const h=['姓名','公司','職稱','部門','手機','電話','Email','通訊','網站','地址','場合','專案','標籤','下次追蹤','最愛','備註','互動次數','最後互動','建立時間','更新時間'],rows=contacts.map(c=>[c.name,c.company,c.title,c.department,c.mobile,c.phone,c.email,c.messenger,c.website,c.address,c.context,c.project,tags(c.tags),c.followUpDate,c.favorite?'是':'否',c.notes,interactions(c).length,(lastInteraction(c)||{}).date||'',c.createdAt,c.updatedAt]),csv='\ufeff'+[h].concat(rows).map(x=>x.map(csvCell).join(',')).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),'人脈名片_'+today()+'.csv');toast('CSV 已匯出')}

function parseVcards(text){return text.split(/(?=BEGIN:VCARD)/i).filter(x=>/BEGIN:VCARD/i.test(x)).map(block=>{const lines=block.replace(/\r\n[ \t]/g,'').split(/\r?\n/),get=key=>{const l=lines.find(x=>new RegExp('^'+key+'(?:;[^:]*)?:','i').test(x));return l?l.slice(l.indexOf(':')+1).replace(/\\n/g,'\n').trim():''},tels=lines.filter(x=>/^TEL/i.test(x)).map(x=>x.slice(x.indexOf(':')+1).trim());return{id:uid(),name:get('FN')||get('N').split(';').filter(Boolean).reverse().join(' '),company:get('ORG').replace(/;/g,' '),title:get('TITLE'),mobile:tels[0]||'',phone:tels[1]||'',email:get('EMAIL'),website:get('URL'),address:get('ADR').replace(/;/g,' ').replace(/\s+/g,' ').trim(),notes:get('NOTE'),department:'',messenger:'',context:'',project:'',tags:[],followUpDate:'',favorite:false,photoData:'',ocrRawText:'',interactions:[],createdAt:nowIso(),updatedAt:nowIso()}}).filter(x=>x.name)}
async function importVcfFiles(files){let n=0;for(const f of files){for(const c of parseVcards(await f.text())){const dup=findDuplicate(c);await dbPut(dup?mergeContact(dup,c):c);n++}}await reload();closeDlg('toolsDialog');toast('已匯入 '+n+' 位聯絡人')}



function openAiAssistant(){closeDlg('captureChoiceDialog');closeDlg('toolsDialog');aiFiles=[];aiPreparedImages=[];renderAiFiles();$('aiResultPaste').value='';$('apiCostAck').checked=false;$('continueApiBtn').disabled=true;openDlg('aiAssistantDialog')}
async function prepareAiAttachments(files){for(const file of files){aiFiles.push(file);if(file.type&&file.type.startsWith('image/')){const slot=aiPreparedImages.length;aiPreparedImages.push({loading:true,name:file.name});renderAiFiles();try{const original=await compress(file,1600,.88),crop=await fastAutoCropCard(original).catch(()=>({dataUrl:original,cropped:false}));aiPreparedImages[slot]={name:file.name,originalPhotoData:original,photoData:crop.dataUrl,cropped:!!crop.cropped}}catch(e){console.error(e);aiPreparedImages[slot]={name:file.name,error:true}}}else aiPreparedImages.push(null)}renderAiFiles()}
function renderAiFiles(){const box=$('aiAttachmentList');if(!box)return;box.innerHTML=aiFiles.length?aiFiles.map((f,i)=>{const p=aiPreparedImages[i],isImg=f.type&&f.type.startsWith('image/'),visual=isImg&&p&&p.photoData?'<img src="'+p.photoData+'" alt="">':'<span>'+(isImg?'▣':'▤')+'</span>',status=isImg?(p&&p.loading?'正在保留原圖與裁切…':p&&p.photoData?(p.cropped?'原始照片已保留 · 已自動裁切':'原始照片已保留 · 使用原圖'):'照片準備中'):(Math.max(1,Math.round(f.size/1024))+' KB');return '<div class="ai-file-chip '+(isImg?'image-file':'')+'"><div class="ai-file-visual">'+visual+'</div><div><strong>'+esc(f.name)+'</strong><small>'+esc(status)+'</small></div><button data-remove-ai-file="'+i+'" aria-label="移除">×</button></div>'}).join(''):'<div class="ai-empty-attachments">尚未加入檔案。可以一次選多張照片或多個檔案。</div>'}
function buildAiPrompt(){const context=$('aiContextText').value.trim(),names=aiFiles.map(f=>f.name);return [
'你是 Little Days 人脈 App 的 AI 整理助手。',
'請分析我附上的名片照片、PDF、Excel、CSV、vCard 或其他聯絡人資料。',
'任務：辨識每一位人物，理解欄位語意，而不是只做 OCR。不要猜；不確定就留空，並列入 needsConfirmation。',
context?'這批資料的補充情境：'+context:'',
names.length?'附件檔名：'+names.join('、'):'',
'',
'請只回傳一個 JSON 物件，不要加 Markdown code fence，不要加其他說明。格式必須是：',
'{',
'  "littleDaysPeopleImport": 1,',
'  "source": "請填你自己的 AI 名稱，例如 Claude",',
'  "summary": "簡短說明辨識結果",',
'  "contacts": [',
'    {',
'      "name": "",',
'      "company": "",',
'      "department": "",',
'      "title": "",',
'      "professionalTitles": [],',
'      "mobile": "",',
'      "phone": "",',
'      "email": "",',
'      "address": "",',
'      "website": "",',
'      "messenger": "",',
'      "context": "",',
'      "project": "",',
'      "tags": [],',
'      "notes": "",',
'      "confidence": {"name":"high","company":"high"},',
'      "needsConfirmation": []',
'    }',
'  ]',
'}',
'',
'規則：',
'1. 手機與公司電話要分開；台灣 09 開頭優先判定為 mobile。',
'2. 公司、部門、職稱、專業頭銜要分開。',
'3. tags 可以依名片內容與補充情境建議，但不要把推測寫進原始欄位。',
'4. 如果同一份檔案有多人，contacts 必須一人一筆。',
'5. 若同一人出現多次，可以合併明確相同的資料；不確定是否同一人則分開。',
'6. 日期／場合／專案若只來自我的補充情境，可以填入 context/project/notes，但不要虛構。'
].filter(Boolean).join('\n')}
async function shareFreeAi(){if(!aiFiles.length)return toast('先加入至少一張照片或一個檔案');const prompt=buildAiPrompt(),instruction=new File([prompt],'LittleDays_給AI的整理指令.txt',{type:'text/plain'}),shareFiles=[...aiFiles,instruction];try{if(navigator.canShare&&navigator.canShare({files:shareFiles})){await navigator.share({title:'Little Days 人脈整理',text:'請讀取附件中的 Little Days 整理指令並直接回傳 JSON。完成後請提醒我：複製全部結果，再回 Little Days 按「從剪貼簿直接回填」。',files:shareFiles});toast('分享選單已開啟；目前可直接選 Claude')}else{await navigator.clipboard.writeText(prompt);toast('整理指令已複製，請把附件與指令交給 AI App')}}catch(e){if(e.name!=='AbortError'){console.error(e);try{await navigator.clipboard.writeText(prompt);toast('分享失敗，已把整理指令複製到剪貼簿')}catch(_){toast('分享失敗，請稍後再試')}}}}
async function applyAiClipboard(){try{if(!navigator.clipboard||!navigator.clipboard.readText)throw new Error('clipboard unsupported');const text=await navigator.clipboard.readText();if(!text.trim())return toast('剪貼簿目前沒有內容');await applyAiPayloadText(text)}catch(e){console.error(e);const d=document.querySelector('.ai-manual-fallback');if(d)d.open=true;toast('iPhone 沒有允許讀剪貼簿，請改用手動貼上')}}
function stripJsonFence(text=''){let s=String(text).trim();s=s.replace(/^\s*```(?:json)?\s*/i,'').replace(/\s*```\s*$/,'').trim();const a=s.indexOf('{'),b=s.lastIndexOf('}');return a>=0&&b>a?s.slice(a,b+1):s}
function aiRawToContact(raw,provider='AI App'){const x=normalizeImportedObject(raw,{kind:'ai-bridge',app:provider,fileName:'AI 整理結果'});x.professionalTitles=Array.isArray(raw.professionalTitles)?raw.professionalTitles:[];if(x.professionalTitles.length){const extra=x.professionalTitles.join('／');x.title=[x.title,extra].filter(Boolean).join('／')}x.tags=[...new Set(tags(raw.tags).concat(tags(raw.suggestedTags||raw.aiTags||[])))];x.aiMeta={provider,mode:'free-bridge',confidence:raw.confidence||{},needsConfirmation:Array.isArray(raw.needsConfirmation)?raw.needsConfirmation:[],importedAt:nowIso()};x.source={kind:'ai-bridge',app:provider,fileName:'AI 整理結果',importedAt:nowIso()};x.derived=smartClassify(x);return x}
async function applyAiPayloadText(text){try{const payload=JSON.parse(stripJsonFence(text)),arr=Array.isArray(payload)?payload:Array.isArray(payload.contacts)?payload.contacts:(payload.contact?[payload.contact]:[]);if(!arr.length)throw new Error('no contacts');const provider=(payload&&payload.source)||'AI App',mapped=arr.map(raw=>aiRawToContact(raw,provider)),prepared=aiPreparedImages.filter(x=>x&&x.photoData);if(prepared.length===mapped.length)prepared.forEach((p,i)=>{mapped[i].photoData=p.photoData;mapped[i].originalPhotoData=p.originalPhotoData;mapped[i].cropMeta={cropped:p.cropped,source:'ai-attachment'}});if(mapped.length===1){const x=mapped[0];pendingAiMeta={source:x.source,derived:x.derived,aiMeta:x.aiMeta};resetForm();setMode(x.photoData?'edit-scan':'edit');['name','company','department','title','mobile','phone','email','address','website','messenger','context','project','notes'].forEach(k=>{if($(k))$(k).value=x[k]||''});$('tags').value=tags(x.tags).join(', ');if(x.photoData){$('photoData').value=x.photoData;$('originalPhotoData').value=x.originalPhotoData||x.photoData;$('photoPreview').innerHTML='<img src="'+x.photoData+'" alt="名片裁切照片">';$('photoPreserveStatus').classList.remove('hidden');$('photoPreserveStatus').innerHTML='<span>✓ 原始照片已保留</span><span>'+(x.originalPhotoData&&x.originalPhotoData!==x.photoData?'✓ 已自動裁切名片':'• 使用原始照片')+'</span>';$('removePhotoBtn').classList.remove('hidden');$('ocrBtn').classList.remove('hidden')}$('advancedDetails').open=!!(x.department||x.title||x.phone||x.address||x.website||x.context||x.project||x.tags.length);closeDlg('aiAssistantDialog');openDlg('editDialog');const n=(x.aiMeta.needsConfirmation||[]).length;toast(n?'AI 已回填；有 '+n+' 個欄位建議確認':'AI 已回填完成');return}const seen=new Set();importCandidates=mapped.map(contact=>{const st=candidateStatus(contact,seen);if((contact.aiMeta.needsConfirmation||[]).length&&st.status==='ready')return{id:uid(),contact,status:'issue',reason:'AI 建議確認：'+contact.aiMeta.needsConfirmation.join('、'),source:contact.source};return{id:uid(),contact,...st,source:contact.source}});importSourceFiles=['AI 整理結果'];importMappingNotes=[{field:'AI',header:'AI 結構化資料'}];closeDlg('aiAssistantDialog');openDlg('importDialog');renderImportPreview();toast('AI 已整理 '+mapped.length+' 位人脈')}catch(e){console.error(e);alert('無法解析這份 AI 結果。請確認有複製完整 JSON，或請 AI 依 Little Days 格式重新輸出。')}}
async function readAiResultFile(file){if(!file)return;try{await applyAiPayloadText(await file.text())}catch(e){console.error(e);toast('讀取 ChatGPT 結果失敗')}}

function openImportCenter(){closeDlg('captureChoiceDialog');closeDlg('toolsDialog');resetImportPreview();renderImportHistory();openDlg('importDialog')}
function resetImportPreview(){importCandidates=[];importMappingNotes=[];importSourceFiles=[];if($('importPreviewSection'))$('importPreviewSection').classList.add('hidden');if($('importCandidateList'))$('importCandidateList').innerHTML='';if($('mappingNotice'))$('mappingNotice').classList.add('hidden')}
function normalizedHeader(v){return norm(v).replace(/[\s_\-\/()（）.:：]+/g,'')}
const FIELD_ALIASES={
 name:['姓名','名字','name','fullname','contactname','中文姓名','displayname','fn'],
 company:['公司','公司名稱','機關','單位','organization','organisation','org','company','companyname','organizationname'],
 title:['職稱','職位','title','position','jobtitle','job','role'],
 department:['部門','部門單位','department','dept','division','team'],
 mobile:['手機','行動電話','mobile','mobilephone','cell','cellphone','cellular'],
 phone:['電話','公司電話','辦公室電話','tel','telephone','phone','workphone','officephone'],
 email:['email','電子郵件','mail','emailaddress','e-mail'],
 website:['網站','網址','website','web','url','homepage'],
 address:['地址','公司地址','address','workaddress','officeaddress'],
 messenger:['line','lineid','通訊','wechat','wechatid','teams'],
 notes:['備註','註記','memo','note','notes','remark','remarks'],
 tags:['標籤','分類','群組','tag','tags','category','categories','group'],
 context:['認識場合','場合','context','event','meeting'],
 project:['專案','計畫','project','projects']
};
function mapHeaders(headers){const mapping={},used=[];headers.forEach((h,i)=>{const nh=normalizedHeader(h);for(const [field,aliases] of Object.entries(FIELD_ALIASES)){if(mapping[field]==null&&aliases.some(a=>normalizedHeader(a)===nh)){mapping[field]=i;used.push({field,header:String(h)});break}}});return{mapping,used}}
function parseCsvRows(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(q){if(ch==='"'&&next==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else if(ch==='"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell.replace(/\r$/,''));if(row.some(x=>String(x).trim()))rows.push(row);return rows}
function guessSourceApp(fileName=''){const n=fileName.toLowerCase();if(n.includes('camcard'))return'CamCard';if(/(^|[-_ ])eight/.test(n)||n.includes('8card'))return'Eight';if(n.includes('hihello'))return'HiHello';if(n.includes('sansan'))return'Sansan';if(n.includes('covve'))return'Covve';if(n.includes('contacts')||n.includes('contact'))return'聯絡人匯出';return'其他 App'}
function smartClassify(x){const text=norm([x.company,x.title,x.department,x.notes].join(' ')),domain=[];let org='其他';if(/政府|市府|縣府|公所|交通局|工務局|建設局|警察局|環保局|教育局|公路局|交通部|內政部|經濟部|署(?:\s|$)/.test(text))org='公部門';else if(/顧問|consult|工程/.test(text))org='工程顧問';else if(/建設|開發|營造|construction|developer/.test(text))org='建設／開發';else if(/大學|學院|研究院|university|college/.test(text))org='學術研究';else if(/銀行|bank|金融|證券/.test(text))org='金融';else if(x.company)org='企業';
 if(/交通|運輸|transport|traffic|mobility/.test(text))domain.push('交通運輸');if(/道路|公路|road|highway/.test(text))domain.push('道路');if(/停車|parking/.test(text))domain.push('停車');if(/自行車|bike|bicycle/.test(text))domain.push('自行車');if(/都市|urban|city planning/.test(text))domain.push('都市規劃');if(/捷運|軌道|metro|rail/.test(text))domain.push('軌道運輸');
 return{organizationType:org,domainTags:[...new Set(domain)],method:'local-smart-rules',generatedAt:nowIso()}}
function contactKey(x){if(x.email)return'e:'+norm(x.email);const m=String(x.mobile||'').replace(/\D/g,'');if(m.length>=8)return'm:'+m;if(x.name&&x.company)return'nc:'+norm(x.name)+'|'+norm(x.company);return''}
function normalizeImportedObject(raw,source={}){const o={},entries=Object.entries(raw||{}),headers=entries.map(([k])=>k),mh=mapHeaders(headers);for(const [field,idx] of Object.entries(mh.mapping)){const key=headers[idx];o[field]=raw[key]==null?'':String(raw[key]).trim()}if(!o.name&&raw.name)o.name=String(raw.name);if(!o.company&&raw.company)o.company=String(raw.company);if(!o.email&&raw.email)o.email=String(raw.email);if(!o.mobile&&raw.mobile)o.mobile=String(raw.mobile);return Object.assign({id:uid(),name:'',company:'',title:'',department:'',mobile:'',phone:'',email:'',messenger:'',website:'',address:'',context:'',project:'',tags:[],followUpDate:'',favorite:false,notes:'',photoData:'',ocrRawText:'',interactions:[],createdAt:nowIso(),updatedAt:nowIso()},o,{tags:tags(o.tags),source:Object.assign({kind:'file',importedAt:nowIso()},source)})}
function candidateStatus(contact,seen){if(!contact.name)return{status:'issue',reason:'缺少姓名'};const key=contactKey(contact);if(key&&seen.has(key))return{status:'duplicate',reason:'匯入檔內重複'};if(key)seen.add(key);const dup=findDuplicate(contact);if(dup)return{status:'duplicate',reason:'與現有人脈重複',duplicateId:dup.id};return{status:'ready',reason:'可直接匯入'}}
function rowsToCandidates(rows,source){if(!rows.length)return{items:[],mapping:[]};const headers=rows[0].map(x=>String(x||'').trim()),mh=mapHeaders(headers),seen=new Set(),items=[];for(const row of rows.slice(1)){if(!row.some(x=>String(x||'').trim()))continue;const raw={};headers.forEach((h,i)=>raw[h]=row[i]??'');const contact=normalizeImportedObject(raw,source),st=candidateStatus(contact,seen);contact.derived=smartClassify(contact);items.push({id:uid(),contact,...st,source})}return{items,mapping:mh.used}}
async function loadXlsx(){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>!!window.XLSX)}
async function parseImportFile(file){
 const ext=(file.name.split('.').pop()||'').toLowerCase(),source={fileName:file.name,app:guessSourceApp(file.name),kind:ext||file.type};
 if(file.type.startsWith('image/')){const item=await enqueuePhotoToInbox(file,{kind:'photo-import',app:'相簿匯入',fileName:file.name});return{photo:item?1:0,items:[],mapping:[]}}
 if(ext==='vcf'){const seen=new Set(),items=parseVcards(await file.text()).map(contact=>{contact.source=Object.assign({importedAt:nowIso()},source);contact.derived=smartClassify(contact);const st=candidateStatus(contact,seen);return{id:uid(),contact,...st,source}});return{items,mapping:[{field:'vCard',header:'標準 vCard 欄位'}]}}
 if(ext==='csv'||file.type.includes('csv'))return rowsToCandidates(parseCsvRows((await file.text()).replace(/^\uFEFF/,'')),source);
 if(ext==='xlsx'||ext==='xls'){await loadXlsx();const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),items=[],mapping=[];for(const name of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:false,defval:''});const out=rowsToCandidates(rows,Object.assign({},source,{sheet:name}));items.push(...out.items);mapping.push(...out.mapping)}return{items,mapping}}
 if(ext==='json'){const x=JSON.parse(await file.text()),arr=Array.isArray(x)?x:Array.isArray(x.contacts)?x.contacts:Array.isArray(x.data)?x.data:[];if(!arr.length)return{items:[{id:uid(),status:'issue',reason:'JSON 找不到聯絡人陣列',contact:{name:'JSON：'+file.name},source}],mapping:[]};const seen=new Set(),items=arr.map(raw=>{const contact=normalizeImportedObject(raw,source);if(raw.photoData)contact.photoData=raw.photoData;if(Array.isArray(raw.interactions))contact.interactions=raw.interactions;contact.derived=smartClassify(contact);const st=candidateStatus(contact,seen);return{id:uid(),contact,...st,source}});return{items,mapping:[]}}
 if(ext==='pdf')return{items:[{id:uid(),status:'issue',reason:'PDF 已接收；需 ChatGPT Vision 後端才能智慧拆分名片',contact:{name:'PDF：'+file.name},source}],mapping:[]};
 return{items:[{id:uid(),status:'issue',reason:'目前尚未支援這個檔案格式',contact:{name:file.name},source}],mapping:[]}
}
function renderImportPreview(){const sec=$('importPreviewSection');if(!sec)return;const total=importCandidates.length,ready=importCandidates.filter(x=>x.status==='ready').length,dups=importCandidates.filter(x=>x.status==='duplicate').length,issues=importCandidates.filter(x=>x.status==='issue').length;sec.classList.toggle('hidden',total===0);$('importTotalCount').textContent=total;$('importReadyCount').textContent=ready;$('importDuplicateCount').textContent=dups;$('importIssueCount').textContent=issues;$('importPreviewTitle').textContent=importSourceFiles.length>1?'多檔匯入預覽':(importSourceFiles[0]||'匯入預覽');const uniqueMap=[...new Map(importMappingNotes.map(x=>[(x.header||'')+'|'+x.field,x])).values()];const notice=$('mappingNotice');if(uniqueMap.length){notice.classList.remove('hidden');notice.innerHTML='<strong>智慧欄位對應</strong><span>'+uniqueMap.slice(0,12).map(x=>esc(x.header)+' → '+esc(x.field)).join('　')+(uniqueMap.length>12?'…':'')+'</span>'}else notice.classList.add('hidden');$('importCandidateList').innerHTML=importCandidates.slice(0,100).map(x=>'<article class="import-candidate '+esc(x.status)+'"><div class="candidate-avatar">'+esc(initials(x.contact.name||'?'))+'</div><div class="candidate-copy"><strong>'+esc(x.contact.name||'未命名資料')+'</strong><span>'+esc([x.contact.company,x.contact.title].filter(Boolean).join(' · ')||x.source.fileName||'')+'</span><small>'+esc((x.contact.derived&&[x.contact.derived.organizationType].concat(x.contact.derived.domainTags||[]).filter(Boolean).join('／'))||x.reason||'')+'</small></div><div class="candidate-status">'+(x.status==='ready'?'✓':x.status==='duplicate'?'重複':'!')+'</div></article>').join('');$('confirmImportBtn').disabled=ready===0;$('confirmImportBtn').textContent=ready?'匯入 '+ready+' 筆可用資料':'沒有可直接匯入的資料'}
async function processImportFiles(files){if(!files.length)return;resetImportPreview();importSourceFiles=files.map(f=>f.name);let photos=0;for(const file of files){try{const out=await parseImportFile(file);photos+=out.photo||0;importCandidates.push(...(out.items||[]));importMappingNotes.push(...(out.mapping||[]))}catch(e){console.error(e);importCandidates.push({id:uid(),status:'issue',reason:'檔案解析失敗',contact:{name:file.name},source:{fileName:file.name,app:guessSourceApp(file.name)}})}}renderImportPreview();if(photos){await renderScanInbox();toast('已把 '+photos+' 張照片送進待整理匣')}if(importCandidates.length)$('importPreviewSection').scrollIntoView({behavior:'smooth',block:'start'})}
async function confirmImport(){const ready=importCandidates.filter(x=>x.status==='ready');if(!ready.length)return;const batchId=uid(),createdIds=[];for(const item of ready){const contact=Object.assign({},item.contact,{id:item.contact.id||uid(),source:Object.assign({},item.contact.source,{importBatchId:batchId})});await dbPut(contact);createdIds.push(contact.id)}const batch={id:batchId,createdAt:nowIso(),files:[...importSourceFiles],count:createdIds.length,createdIds,status:'active'};await batchPut(batch);await reload();importCandidates=importCandidates.filter(x=>x.status!=='ready');renderImportPreview();await renderImportHistory();toast('已匯入 '+createdIds.length+' 位人脈')}
async function renderImportHistory(){if(!$('importHistoryList'))return;const batches=(await batchAll()).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,8);$('importHistoryList').innerHTML=batches.length?batches.map(b=>'<article class="import-history-item"><div><strong>'+esc((b.files||[]).join('、')||'匯入批次')+'</strong><span>'+esc(new Date(b.createdAt).toLocaleString('zh-TW'))+' · '+b.count+' 筆</span></div>'+(b.status==='active'?'<button data-rollback-batch="'+esc(b.id)+'">復原</button>':'<span class="rolled-back">已復原</span>')+'</article>').join(''):'<div class="timeline-empty">還沒有檔案匯入紀錄。</div>'}
async function rollbackImportBatch(id){const batch=await batchGet(id);if(!batch||batch.status!=='active')return;if(!confirm('要復原這次匯入的 '+batch.count+' 筆資料嗎？\n\n只會刪除這個批次新建立的人脈。'))return;for(const cid of batch.createdIds||[])await dbDelete(cid);batch.status='rolledback';batch.rolledBackAt=nowIso();await batchPut(batch);await reload();await renderImportHistory();toast('已復原這次匯入')}


function categoryStats(){const tagMap=new Map(),companyMap=new Map();for(const c of contacts){for(const v of categoryValues(c))tagMap.set(v,(tagMap.get(v)||0)+1);if(c.company)companyMap.set(c.company,(companyMap.get(c.company)||0)+1)}const sorter=(a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0]),'zh-Hant');return{tags:[...tagMap].sort(sorter),companies:[...companyMap].sort(sorter)}}
function openCategories(){closeDlg('toolsDialog');renderCategories();openDlg('categoryDialog')}
function renderCategories(){const s=categoryStats();$('categoryAllCount').textContent=contacts.length;$('categoryAllBtn').classList.toggle('active',!activeCategory);$('categoryList').innerHTML=s.tags.length?s.tags.map(([name,count])=>'<button class="category-row '+(activeCategory==='tag:'+name?'active':'')+'" data-category-key="tag:'+esc(name)+'"><span>'+esc(name)+'</span><b>'+count+'</b></button>').join(''):'<div class="timeline-empty">還沒有標籤或 AI 分類。</div>';$('companyCategoryList').innerHTML=s.companies.length?s.companies.slice(0,40).map(([name,count])=>'<button class="category-row '+(activeCategory==='company:'+name?'active':'')+'" data-category-key="company:'+esc(name)+'"><span>'+esc(name)+'</span><b>'+count+'</b></button>').join(''):'<div class="timeline-empty">還沒有公司資料。</div>'}
function renderHomeCategories(){const rail=$('homeCategoryRail');if(!rail)return;const s=categoryStats(),items=[...s.tags.slice(0,10).map(([name,count])=>({key:'tag:'+name,name,count})),...s.companies.slice(0,8).map(([name,count])=>({key:'company:'+name,name,count}))];rail.innerHTML='<button class="home-category-chip '+(!activeCategory?'active':'')+'" data-home-category="">全部 <b>'+contacts.length+'</b></button>'+items.map(x=>'<button class="home-category-chip '+(activeCategory===x.key?'active':'')+'" data-home-category="'+esc(x.key)+'">'+esc(x.name)+' <b>'+x.count+'</b></button>').join('')}
function selectCategory(key=''){activeCategory=key;activeFilter='all';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));closeDlg('categoryDialog');render();window.scrollTo({top:0,behavior:'smooth'})}
function renderAlphabet(list){const rail=$('alphabetRail');if(!rail)return;const keys=[...new Set(list.map(c=>alphaKey(c.name)))],order='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').filter(x=>keys.includes(x));if(keys.includes('#'))order.push('#');rail.innerHTML=order.map(k=>'<button data-alpha-jump="'+k+'">'+k+'</button>').join('');rail.classList.toggle('hidden',order.length<2)}
function jumpAlpha(k){$('sortSelect').value='name-asc';render();requestAnimationFrame(()=>{const safe=window.CSS&&CSS.escape?CSS.escape(k):k.replace(/"/g,'');const el=document.querySelector('.contact-card[data-alpha="'+safe+'"]');if(el)el.scrollIntoView({behavior:'smooth',block:'center'})})}
function duplicateGroups(){const maps={email:new Map(),mobile:new Map(),nameCompany:new Map()};for(const c of contacts){const e=norm(c.email),m=String(c.mobile||'').replace(/\D/g,''),nc=c.name&&c.company?norm(c.name)+'|'+norm(c.company):'';if(e){if(!maps.email.has(e))maps.email.set(e,[]);maps.email.get(e).push(c)}if(m.length>=8){if(!maps.mobile.has(m))maps.mobile.set(m,[]);maps.mobile.get(m).push(c)}if(nc){if(!maps.nameCompany.has(nc))maps.nameCompany.set(nc,[]);maps.nameCompany.get(nc).push(c)}}const seen=new Set(),groups=[];for(const map of Object.values(maps)){for(const arr of map.values()){if(arr.length<2)continue;const ids=arr.map(x=>x.id).sort(),key=ids.join('|');if(!seen.has(key)){seen.add(key);groups.push(arr)}}}return groups}
function isIncomplete(c){return !c.company||!(c.mobile||c.phone||c.email)}
function isStale(c){const last=lastInteraction(c),base=last&&last.date?new Date(last.date+'T12:00:00'):new Date(c.updatedAt||c.createdAt||0);return base.getTime()>0&&Date.now()-base.getTime()>365*864e5}
function healthData(){const confirm=contacts.filter(c=>c.aiMeta&&Array.isArray(c.aiMeta.needsConfirmation)&&c.aiMeta.needsConfirmation.length),incomplete=contacts.filter(isIncomplete),stale=contacts.filter(isStale),duplicates=duplicateGroups(),ids=new Set([...confirm,...incomplete,...stale].map(x=>x.id));duplicates.flat().forEach(x=>ids.add(x.id));return{confirm,incomplete,stale,duplicates,total:ids.size}}
function renderManagementHints(){const h=healthData();if($('healthHint'))$('healthHint').textContent=h.total?h.total+' 位需要留意':'目前資料很乾淨';if($('healthBadge')){$('healthBadge').textContent=h.total;$('healthBadge').classList.toggle('hidden',!h.total)}}
function openHealth(){closeDlg('toolsDialog');renderHealth('all');openDlg('healthDialog')}
function healthSectionButton(type,label,count){return '<button data-health-type="'+type+'"><strong>'+count+'</strong><span>'+label+'</span></button>'}
function renderHealth(type='all'){const h=healthData();$('healthHeroTitle').textContent=h.total?'有 '+h.total+' 位值得看一下':'資料很乾淨';$('healthHeroText').textContent=h.total?'不用整理全部，只處理下面例外。':'目前沒有重複、缺資料或 AI 待確認。';$('healthSummary').innerHTML=healthSectionButton('confirm','AI 待確認',h.confirm.length)+healthSectionButton('duplicate','疑似重複',h.duplicates.length)+healthSectionButton('incomplete','資料不完整',h.incomplete.length)+healthSectionButton('stale','久未聯絡',h.stale.length);let items=[];if(type==='confirm'||type==='all')items.push(...h.confirm.map(c=>({c,label:'AI 待確認 '+(c.aiMeta.needsConfirmation||[]).join('、'),confirm:true})));if(type==='incomplete'||type==='all')items.push(...h.incomplete.map(c=>({c,label:!c.company?'缺公司資訊':'缺聯絡方式'})));if(type==='stale'||type==='all')items.push(...h.stale.map(c=>({c,label:'超過一年沒有更新／互動'})));if(type==='duplicate'||type==='all')h.duplicates.forEach(g=>items.push({group:g,label:'疑似同一人：'+g.map(x=>x.name).join(' / ')}));const seen=new Set();items=items.filter(x=>{const k=x.group?'g:'+x.group.map(y=>y.id).sort().join('|'):'c:'+x.c.id+'|'+x.label;if(seen.has(k))return false;seen.add(k);return true});$('healthDetailList').innerHTML=items.length?items.map(x=>x.group?'<article class="health-item duplicate"><span class="health-mark">≋</span><div><strong>'+esc(x.label)+'</strong><small>'+esc(x.group.map(y=>[y.company,y.email||y.mobile].filter(Boolean).join(' · ')).join('｜'))+'</small></div><button data-contact-id="'+esc(x.group[0].id)+'">查看</button></article>':'<article class="health-item '+(x.confirm?'needs-confirm':'')+'"><span class="health-mark">!</span><div><strong>'+esc(x.c.name)+'</strong><small>'+esc(x.label)+' · '+esc(x.c.company||'未填公司')+'</small></div><div class="health-actions">'+(x.confirm?'<button class="confirm-ok" data-confirm-ai-id="'+esc(x.c.id)+'">確認無誤</button>':'')+'<button data-contact-id="'+esc(x.c.id)+'">查看</button></div></article>').join(''):'<div class="health-clean">✓ 這一類目前沒有需要處理的項目</div>'}

function getMyCard(){try{return JSON.parse(localStorage.getItem(MY_CARD_KEY)||'{}')}catch(e){return{}}}
function setMyCard(c){localStorage.setItem(MY_CARD_KEY,JSON.stringify(c))}
function fillMyCard(){const c=getMyCard();$('myName').value=c.name||'';$('myCompany').value=c.company||'';$('myTitle').value=c.title||'';$('myMobile').value=c.mobile||'';$('myEmail').value=c.email||'';$('myWebsite').value=c.website||'';renderMyCard(c)}
function myCardFromForm(){return{name:$('myName').value.trim(),company:$('myCompany').value.trim(),title:$('myTitle').value.trim(),mobile:$('myMobile').value.trim(),email:$('myEmail').value.trim(),website:$('myWebsite').value.trim()}}
async function loadQrLib(){await loadScript('https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.min.js',()=>!!window.qrcode)}
async function renderMyCard(c){$('myCardInitials').textContent=initials(c.name||'我');$('myCardPreviewName').textContent=c.name||'設定你的名片';$('myCardPreviewMeta').textContent=[c.company,c.title].filter(Boolean).join(' · ')||'分享時不用再交換紙本名片';$('qrBox').innerHTML='<span>QR</span>';if(!c.name)return;try{await loadQrLib();const qr=qrcode(0,'M');qr.addData(vcard(c));qr.make();$('qrBox').innerHTML=qr.createImgTag(4,0)}catch(e){console.error(e)}}
async function saveMyCard(e){e.preventDefault();const c=myCardFromForm();setMyCard(c);await renderMyCard(c);toast('我的名片已儲存')}
async function shareMyCard(){const c=getMyCard();if(!c.name)return toast('先填姓名並儲存我的名片');await shareVcard(c)}

function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('這台瀏覽器暫不支援語音辨識');const r=new R();r.lang='zh-TW';r.interimResults=false;r.maxAlternatives=1;$('voiceNoteBtn').textContent='●';r.onresult=e=>{const t=e.results[0][0].transcript.trim();$('notes').value=[$('notes').value.trim(),t].filter(Boolean).join(' ')};r.onerror=()=>toast('語音辨識沒有成功');r.onend=()=>$('voiceNoteBtn').textContent='🎙';r.start()}
async function seedDemo(){const a=[{name:'陳怡君',company:'新北市政府',title:'科長',department:'交通規劃科',mobile:'0912-345-678',email:'yijun@example.gov.tw',context:'專案會議',project:'自行車路網',tags:['公部門','新北','自行車'],followUpDate:today(),favorite:true,notes:'關心轉乘節點與斷鏈改善。',interactions:[{id:uid(),date:today(),type:'會議',note:'討論汐科周邊轉乘與斷鏈改善方向。'}]},{name:'林志宏',company:'遠見工程顧問',title:'協理',mobile:'0933-222-111',email:'jhlin@example.com',context:'研討會',project:'交流道改善',tags:['顧問','道路'],favorite:false,notes:'後續可討論綜規合作。',interactions:[]},{name:'Amy Wang',company:'Urban Mobility Lab',title:'Project Manager',email:'amy@example.com',context:'論壇',tags:['國際','Mobility'],favorite:false,notes:'英文聯繫。',interactions:[]}];for(const d of a)await dbPut(Object.assign({id:uid(),photoData:'',phone:'',messenger:'',website:'',address:'',department:d.department||'',ocrRawText:'',createdAt:nowIso(),updatedAt:nowIso()},d));await reload();toast('已載入示範資料')}
function setFilter(f){activeFilter=f;activeCategory='';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));document.querySelectorAll('.nav-item[data-nav]').forEach(b=>b.classList.remove('active'));if(f==='all')document.querySelector('[data-nav="contacts"]')?.classList.add('active');if(f==='favorite')document.querySelector('[data-nav="favorites"]')?.classList.add('active');if(f==='followup')document.querySelector('[data-nav="followup"]')?.classList.add('active');render();window.scrollTo({top:0,behavior:'smooth'})}

function bind(){
 $('aiAssistantBtn').onclick=openAiAssistant;
 $('quickAddBtn').onclick=openQuick;
 $('emptyScanBtn').onclick=openAiAssistant;
 $('emptyAddBtn').onclick=openQuick;
 $('fabAdd').onclick=()=>openDlg('captureChoiceDialog');
 $('choiceAiBtn').onclick=openAiAssistant;
 $('choiceScanBtn').onclick=openScan;
 $('choiceImportBtn').onclick=openImportCenter;
 $('choiceQuickBtn').onclick=openQuick;

 $('toolsTopBtn').onclick=()=>openDlg('toolsDialog');
 $('openAllCategoriesBtn').onclick=openCategories;
 $('categoryToolBtn').onclick=openCategories;
 $('healthCheckBtn').onclick=openHealth;
 $('healthToolBtn').onclick=openHealth;
 $('categoryAllBtn').onclick=()=>selectCategory('');
 $('categoryList').onclick=e=>{const b=e.target.closest('[data-category-key]');if(b)selectCategory(b.dataset.categoryKey)};
 $('companyCategoryList').onclick=e=>{const b=e.target.closest('[data-category-key]');if(b)selectCategory(b.dataset.categoryKey)};
 $('homeCategoryRail').onclick=e=>{const b=e.target.closest('[data-home-category]');if(b)selectCategory(b.dataset.homeCategory||'')};
 $('alphabetRail').onclick=e=>{const b=e.target.closest('[data-alpha-jump]');if(b)jumpAlpha(b.dataset.alphaJump)};
 $('healthSummary').onclick=e=>{const b=e.target.closest('[data-health-type]');if(b)renderHealth(b.dataset.healthType)};
 $('healthDetailList').onclick=async e=>{
   const confirmBtn=e.target.closest('[data-confirm-ai-id]');
   if(confirmBtn){await confirmAiContactById(confirmBtn.dataset.confirmAiId);return}
   const b=e.target.closest('[data-contact-id]');
   if(b){closeDlg('healthDialog');showDetail(b.dataset.contactId)}
 };

 $('contactForm').addEventListener('submit',saveForm);
 $('deleteBtn').onclick=delCurrent;
 $('takePhotoBtn').onclick=()=>{captureTarget='edit';$('cameraInput').click()};
 $('choosePhotoBtn').onclick=()=>{captureTarget='edit';$('photoInput').click()};
 $('ocrBtn').onclick=runOCR;
 $('batchCameraBtn').onclick=()=>{captureTarget='batch';$('cameraInput').click()};
 $('batchAlbumBtn').onclick=()=>{captureTarget='batch';$('photoInput').click()};
 $('batchDoneBtn').onclick=()=>{closeDlg('scanBatchDialog');toast(batchCaptured?'已收下 '+batchCaptured+' 張，會繼續整理':'已完成')};

 $('cameraInput').addEventListener('change',async e=>{const file=e.target.files[0];if(captureTarget==='batch')await addScanToInbox(file);else await readPhoto(file);e.target.value='';captureTarget='edit'});
 $('photoInput').addEventListener('change',async e=>{const files=[...e.target.files];if(captureTarget==='batch'){for(const file of files)await addScanToInbox(file)}else if(captureTarget==='importphotos'){for(const file of files)await enqueuePhotoToInbox(file,{kind:'photo-import',app:'相簿匯入',fileName:file.name});await renderScanInbox();if(files.length)toast('已把 '+files.length+' 張照片送進待整理匣')}else if(files[0])await readPhoto(files[0]);e.target.value='';captureTarget='edit'});
 $('removePhotoBtn').onclick=()=>{$('photoData').value='';$('originalPhotoData').value='';$('ocrRawText').value='';$('photoPreview').innerHTML='<span class="photo-placeholder-icon">▣</span><span>拍一張名片，讓我幫你讀</span>';$('photoPreserveStatus').classList.add('hidden');$('removePhotoBtn').classList.add('hidden');$('ocrBtn').classList.add('hidden');$('rawOcrDetails').classList.add('hidden')};

 $('aiAttachBtn').onclick=()=>$('aiFilesInput').click();
 $('aiFilesInput').onchange=async e=>{const files=[...e.target.files];e.target.value='';if(files.length){await prepareAiAttachments(files);toast('已保留原始照片並準備名片裁切版')}};
 $('aiAttachmentList').onclick=e=>{const b=e.target.closest('[data-remove-ai-file]');if(!b)return;const idx=Number(b.dataset.removeAiFile);aiFiles.splice(idx,1);aiPreparedImages.splice(idx,1);renderAiFiles()};
 $('aiFreeSendBtn').onclick=shareFreeAi;
 $('aiClipboardBtn').onclick=applyAiClipboard;
 $('aiResultFileBtn').onclick=()=>$('aiResultFileInput').click();
 $('aiResultFileInput').onchange=async e=>{await readAiResultFile(e.target.files[0]);e.target.value=''};
 $('aiApplyResultBtn').onclick=()=>applyAiPayloadText($('aiResultPaste').value);

 $('paidModeBtn').onclick=()=>{closeDlg('aiAssistantDialog');$('apiCostAck').checked=false;$('continueApiBtn').disabled=true;openDlg('apiCostDialog')};
 $('apiCostAck').onchange=e=>$('continueApiBtn').disabled=!e.target.checked;
 $('keepFreeBtn').onclick=()=>{closeDlg('apiCostDialog');openDlg('aiAssistantDialog')};
 $('continueApiBtn').onclick=()=>{if(!$('apiCostAck').checked)return;closeDlg('apiCostDialog');openDlg('apiSetupDialog')};
 $('backToFreeBtn').onclick=()=>{closeDlg('apiSetupDialog');openDlg('aiAssistantDialog')};

 $('importPhotosBtn').onclick=()=>{captureTarget='importphotos';$('photoInput').click()};
 $('importFilesBtn').onclick=()=>$('importFilesInput').click();
 $('importFilesInput').onchange=async e=>{await processImportFiles([...e.target.files]);e.target.value=''};
 $('clearImportPreviewBtn').onclick=resetImportPreview;
 $('cancelImportBtn').onclick=resetImportPreview;
 $('confirmImportBtn').onclick=confirmImport;
 $('importHistoryList').onclick=e=>{const b=e.target.closest('[data-rollback-batch]');if(b)rollbackImportBatch(b.dataset.rollbackBatch)};

 $('voiceNoteBtn').onclick=startVoice;
 document.querySelectorAll('#contextSuggestions button').forEach(b=>b.onclick=()=>{$('context').value=b.dataset.context;$('advancedDetails').open=true;toast('已記為「'+b.dataset.context+'」')});
 document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>closeDlg(b.dataset.closeDialog));
 document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));

 $('contactsList').onclick=e=>{const card=e.target.closest('.contact-card');if(card)showDetail(card.dataset.id)};
 $('scanInboxList').onclick=e=>{const card=e.target.closest('[data-scan-id]');if(card)reviewInboxItem(card.dataset.scanId)};
 $('searchInput').oninput=()=>{$('searchInput').parentElement.classList.toggle('has-text',!!$('searchInput').value);render()};
 $('clearSearch').onclick=()=>{$('searchInput').value='';$('searchInput').parentElement.classList.remove('has-text');render();$('searchInput').focus()};
 $('sortSelect').onchange=render;
 document.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));
 document.querySelectorAll('[data-jump-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.jumpFilter));

 $('detailAiConfirmBtn').onclick=confirmAiContact;
 $('detailFavoriteBtn').onclick=toggleFavorite;
 $('detailEditBtn').onclick=editDetail;
 $('detailShareBtn').onclick=shareCurrent;
 $('calendarBtn').onclick=addCalendar;
 $('addInteractionBtn').onclick=()=>{$('interactionDate').value=today();$('interactionComposer').classList.remove('hidden')};
 $('cancelInteractionBtn').onclick=()=>$('interactionComposer').classList.add('hidden');
 $('saveInteractionBtn').onclick=saveInteraction;

 $('myCardBtn').onclick=()=>{fillMyCard();openDlg('myCardDialog')};
 $('myCardToolBtn').onclick=()=>{closeDlg('toolsDialog');fillMyCard();openDlg('myCardDialog')};
 $('myCardForm').onsubmit=saveMyCard;
 $('shareMyCardBtn').onclick=shareMyCard;

 $('aiAssistantToolBtn').onclick=openAiAssistant;
 $('importCenterToolBtn').onclick=openImportCenter;
 $('backupBtn').onclick=openBackupCenter;
 $('openBackupCenterBtn').onclick=openBackupCenter;
 $('fullBackupBtn').onclick=backup;
 $('mergeRestoreBtn').onclick=()=>{restoreMode='merge';$('restoreInput').click()};
 $('replaceRestoreBtn').onclick=()=>{restoreMode='replace';$('restoreInput').click()};
 $('restoreInput').onchange=async e=>{await restoreFile(e.target.files[0],restoreMode);e.target.value=''};
 $('csvBtn').onclick=exportCsv;
 $('seedDemoBtn').onclick=seedDemo
}

async function init(){try{db=await openDB();bind();await reload();setTimeout(processScanQueue,700);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){console.error(e);alert('無法啟動本機資料庫，請確認瀏覽器允許網站儲存資料。')}}
init();
